import '../models/quiz_models.dart';

class QuizData {
  static List<QuizQuestion> easy = [
    QuizQuestion(
      id: 'easy_1',
      difficulty: 'Easy',
      category: 'Candlestick',
      question: 'What does a single green (or white) candlestick typically indicate?',
      options: ['Close price higher than open (bullish)', 'Close price lower than open (bearish)', 'No price movement occurred', 'Only used for the daily timeframe'],
      correctIndex: 0,
      explanation: 'A bullish (green/white) candle closes above where it opened, showing buying pressure during that period.',
    ),
    QuizQuestion(
      id: 'easy_2',
      difficulty: 'Easy',
      category: 'Candlestick',
      question: 'A Doji candlestick pattern is characterized by:',
      options: ['A very long body with small wicks', 'Open and close prices being nearly equal', 'Two candles of opposite colors', 'A gap between two candles'],
      correctIndex: 1,
      explanation: 'A Doji forms when the open and close are virtually the same, creating a thin or cross-like body that signals indecision.',
    ),
    QuizQuestion(
      id: 'easy_3',
      difficulty: 'Easy',
      category: 'Candlestick',
      question: 'The Hammer candlestick pattern typically appears at:',
      options: ['The top of an uptrend', 'The bottom of a downtrend', 'The middle of a sideways range', 'Only on weekly charts'],
      correctIndex: 1,
      explanation: 'A Hammer has a small body near the top with a long lower wick, signaling a potential bullish reversal after a downtrend.',
    ),
    QuizQuestion(
      id: 'easy_4',
      difficulty: 'Easy',
      category: 'Candlestick',
      question: 'What is the main visual difference between a Hammer and a Hanging Man?',
      options: ['The color of the body', 'Nothing, they look identical but occur in different trends', 'The length of the upper wick', 'The number of candles involved'],
      correctIndex: 1,
      explanation: 'Both patterns share the same shape (small body, long lower wick) but the Hammer appears after a downtrend while the Hanging Man appears after an uptrend.',
    ),
    QuizQuestion(
      id: 'easy_5',
      difficulty: 'Easy',
      category: 'Candlestick',
      question: 'A Bullish Engulfing pattern consists of:',
      options: ['A small bearish candle followed by a larger bullish candle that covers it', 'A large bullish candle followed by a small bearish candle', 'Three consecutive bullish candles', 'A single long bullish candle'],
      correctIndex: 0,
      explanation: 'The second bullish candle\'s body completely engulfs the prior bearish candle\'s body, signaling a potential upward reversal.',
    ),
    QuizQuestion(
      id: 'easy_6',
      difficulty: 'Easy',
      category: 'Candlestick',
      question: 'A Bearish Engulfing pattern signals:',
      options: ['Continuation of an uptrend', 'A potential reversal to the downside', 'No directional bias', 'Increased volatility only'],
      correctIndex: 1,
      explanation: 'A larger bearish candle engulfing the prior bullish candle\'s body suggests sellers have taken control.',
    ),
    QuizQuestion(
      id: 'easy_7',
      difficulty: 'Easy',
      category: 'Candlestick',
      question: 'The Shooting Star pattern has which shape?',
      options: ['Small body near the bottom with a long upper wick', 'Small body near the top with a long lower wick', 'Long body with no wicks', 'Equal upper and lower wicks'],
      correctIndex: 0,
      explanation: 'A Shooting Star has a small real body near the candle\'s low with a long upper shadow, appearing after an uptrend as a bearish signal.',
    ),
    QuizQuestion(
      id: 'easy_8',
      difficulty: 'Easy',
      category: 'Candlestick',
      question: 'An Inverted Hammer appears after a downtrend and suggests:',
      options: ['Continued selling pressure', 'A possible bullish reversal', 'A confirmed breakout', 'Market closure'],
      correctIndex: 1,
      explanation: 'Similar shape to a Shooting Star but appearing after a downtrend, it hints buyers are starting to push back against sellers.',
    ),
    QuizQuestion(
      id: 'easy_9',
      difficulty: 'Easy',
      category: 'Candlestick',
      question: 'A Marubozu candlestick has:',
      options: ['No upper or lower wicks', 'Only an upper wick', 'Only a lower wick', 'Equal wicks on both sides'],
      correctIndex: 0,
      explanation: 'A Marubozu candle has almost no wicks, showing one side controlled price action from open to close.',
    ),
    QuizQuestion(
      id: 'easy_10',
      difficulty: 'Easy',
      category: 'Candlestick',
      question: 'A Spinning Top candlestick reflects:',
      options: ['Strong trending momentum', 'Market indecision with a small body and wicks on both sides', 'A confirmed breakout', 'Extremely low volume days only'],
      correctIndex: 1,
      explanation: 'The small body with wicks on both sides shows neither buyers nor sellers gained control during that period.',
    ),
    QuizQuestion(
      id: 'easy_11',
      difficulty: 'Easy',
      category: 'Candlestick',
      question: 'In a candlestick chart, what does the wick (or shadow) represent?',
      options: ['The opening price only', 'The highest and lowest prices reached during the period', 'The average price', 'The volume traded'],
      correctIndex: 1,
      explanation: 'Wicks show the high and low extremes reached during the candle\'s timeframe, beyond the open/close body.',
    ),
    QuizQuestion(
      id: 'easy_12',
      difficulty: 'Easy',
      category: 'Candlestick',
      question: 'A red (or black) candlestick typically means:',
      options: ['Close price higher than open', 'Close price lower than open', 'No trades occurred', 'The market is closed'],
      correctIndex: 1,
      explanation: 'A bearish candle closes below its opening price, indicating selling pressure during that period.',
    ),
    QuizQuestion(
      id: 'easy_13',
      difficulty: 'Easy',
      category: 'Chart Pattern',
      question: 'In technical analysis, a support level is:',
      options: ['A price area where buying interest has historically stopped declines', 'A price area where selling interest has historically stopped rallies', 'The exact opening price of the day', 'A broker\'s minimum deposit requirement'],
      correctIndex: 0,
      explanation: 'Support is a price zone where demand has historically been strong enough to halt or reverse a downward move.',
    ),
    QuizQuestion(
      id: 'easy_14',
      difficulty: 'Easy',
      category: 'Chart Pattern',
      question: 'A resistance level is:',
      options: ['A price area where demand overwhelms supply', 'A price area where supply has historically stopped rallies', 'The lowest price ever recorded', 'A type of candlestick'],
      correctIndex: 1,
      explanation: 'Resistance is where selling pressure has historically been strong enough to cap price advances.',
    ),
    QuizQuestion(
      id: 'easy_15',
      difficulty: 'Easy',
      category: 'Chart Pattern',
      question: 'An uptrend is generally defined by:',
      options: ['A series of lower highs and lower lows', 'A series of higher highs and higher lows', 'Sideways price movement only', 'Randomly fluctuating prices'],
      correctIndex: 1,
      explanation: 'An uptrend is confirmed by successive price swings making higher highs and higher lows.',
    ),
    QuizQuestion(
      id: 'easy_16',
      difficulty: 'Easy',
      category: 'Chart Pattern',
      question: 'A downtrend is generally defined by:',
      options: ['A series of higher highs and higher lows', 'A series of lower highs and lower lows', 'Flat price action', 'Increasing volume only'],
      correctIndex: 1,
      explanation: 'A downtrend shows successive swings making lower highs and lower lows.',
    ),
    QuizQuestion(
      id: 'easy_17',
      difficulty: 'Easy',
      category: 'Chart Pattern',
      question: 'The Head and Shoulders chart pattern is typically used to signal:',
      options: ['Trend continuation', 'A possible trend reversal', 'Increased liquidity', 'A change in broker spread'],
      correctIndex: 1,
      explanation: 'The pattern (left shoulder, higher head, right shoulder) commonly appears at market tops and signals a possible bearish reversal.',
    ),
    QuizQuestion(
      id: 'easy_18',
      difficulty: 'Easy',
      category: 'Chart Pattern',
      question: 'A Double Top chart pattern suggests:',
      options: ['The price may reverse downward after failing to break a resistance twice', 'The price will definitely continue rising', 'It is a bullish continuation signal', 'It only appears on the 1-minute chart'],
      correctIndex: 0,
      explanation: 'Two failed attempts to break above the same resistance level often precede a bearish reversal.',
    ),
    QuizQuestion(
      id: 'easy_19',
      difficulty: 'Easy',
      category: 'Chart Pattern',
      question: 'A Double Bottom chart pattern suggests:',
      options: ['A bearish reversal', 'A bullish reversal after failing twice to break below support', 'Sideways consolidation forever', 'A broker execution error'],
      correctIndex: 1,
      explanation: 'Price testing and holding the same support level twice often signals a bullish reversal.',
    ),
    QuizQuestion(
      id: 'easy_20',
      difficulty: 'Easy',
      category: 'Chart Pattern',
      question: 'A trend line is drawn by connecting:',
      options: ['Random candle bodies', 'At least two significant swing highs or swing lows', 'Only the opening prices of the week', 'The broker\'s bid and ask prices'],
      correctIndex: 1,
      explanation: 'Trend lines connect a series of swing highs (downtrend) or swing lows (uptrend) to visualize the trend\'s direction.',
    ),
  ];

  static List<QuizQuestion> medium = [
    QuizQuestion(
      id: 'medium_1',
      difficulty: 'Medium',
      category: 'Candlestick',
      question: 'The Three White Soldiers pattern consists of:',
      options: ['Three consecutive bullish candles each closing higher than the last', 'Three consecutive bearish candles', 'One large candle followed by two dojis', 'A gap up followed by a gap down'],
      correctIndex: 0,
      explanation: 'Three strong bullish candles in a row, each closing near its high, signals strong bullish momentum.',
    ),
    QuizQuestion(
      id: 'medium_2',
      difficulty: 'Medium',
      category: 'Candlestick',
      question: 'The Three Black Crows pattern consists of:',
      options: ['Three consecutive bullish candles', 'Three consecutive bearish candles each closing lower than the last', 'A single large bearish candle', 'Two dojis and one bullish candle'],
      correctIndex: 1,
      explanation: 'Three strong bearish candles in a row signals strong bearish momentum.',
    ),
    QuizQuestion(
      id: 'medium_3',
      difficulty: 'Medium',
      category: 'Candlestick',
      question: 'A Piercing Line pattern is a bullish reversal formed when:',
      options: ['A bullish candle closes above the midpoint of the prior bearish candle\'s body', 'A bearish candle closes below the prior candle\'s low', 'Two identical dojis appear back to back', 'Price gaps up and stays flat'],
      correctIndex: 0,
      explanation: 'The second bullish candle opens lower but closes above the midpoint of the first bearish candle\'s body, showing a shift in momentum.',
    ),
    QuizQuestion(
      id: 'medium_4',
      difficulty: 'Medium',
      category: 'Candlestick',
      question: 'A Dark Cloud Cover pattern is a bearish reversal formed when:',
      options: ['A bearish candle opens above the prior high then closes below the midpoint of the prior bullish candle\'s body', 'A bullish candle engulfs the prior candle', 'Three dojis appear in a row', 'Price gaps down sharply'],
      correctIndex: 0,
      explanation: 'The bearish candle opens with strength but closes deep into the prior bullish candle\'s body, signaling weakening buyers.',
    ),
    QuizQuestion(
      id: 'medium_5',
      difficulty: 'Medium',
      category: 'Candlestick',
      question: 'A Bullish Harami pattern is formed when:',
      options: ['A small bullish candle is contained within the body of a larger prior bearish candle', 'A large bullish candle engulfs the prior candle', 'Two long bearish candles appear together', 'Price gaps up on high volume'],
      correctIndex: 0,
      explanation: 'The small bullish candle sitting inside the prior larger bearish candle signals a weakening downtrend.',
    ),
    QuizQuestion(
      id: 'medium_6',
      difficulty: 'Medium',
      category: 'Candlestick',
      question: 'A Bearish Harami pattern is formed when:',
      options: ['A small bearish candle is contained within the body of a larger prior bullish candle', 'A large bearish candle engulfs the prior candle', 'Two long bullish candles appear together', 'Price gaps down on low volume'],
      correctIndex: 0,
      explanation: 'The small bearish candle sitting inside the prior larger bullish candle signals a weakening uptrend.',
    ),
    QuizQuestion(
      id: 'medium_7',
      difficulty: 'Medium',
      category: 'Candlestick',
      question: 'A Tweezer Top pattern occurs when:',
      options: ['Two candles form matching highs at a resistance area, signaling a bearish reversal', 'Two candles form matching lows at a support area', 'Three candles form a staircase pattern', 'A single candle has two upper wicks'],
      correctIndex: 0,
      explanation: 'Matching highs on consecutive candles at resistance suggest buyers failed twice to push price higher.',
    ),
    QuizQuestion(
      id: 'medium_8',
      difficulty: 'Medium',
      category: 'Candlestick',
      question: 'A Tweezer Bottom pattern occurs when:',
      options: ['Two candles form matching lows at a support area, signaling a bullish reversal', 'Two candles form matching highs at a resistance area', 'Three candles form a descending pattern', 'A single candle has two lower wicks only'],
      correctIndex: 0,
      explanation: 'Matching lows on consecutive candles at support suggest sellers failed twice to push price lower.',
    ),
    QuizQuestion(
      id: 'medium_9',
      difficulty: 'Medium',
      category: 'Candlestick',
      question: 'The Rising Three Methods pattern is a bullish continuation pattern made of:',
      options: ['A long bullish candle, three small bearish candles staying within its range, then another long bullish candle', 'Five consecutive bearish candles', 'A doji surrounded by two long candles', 'A gap up followed by a gap down'],
      correctIndex: 0,
      explanation: 'The small pullback candles staying contained show the uptrend is only pausing before continuing.',
    ),
    QuizQuestion(
      id: 'medium_10',
      difficulty: 'Medium',
      category: 'Candlestick',
      question: 'The Falling Three Methods pattern is a bearish continuation pattern made of:',
      options: ['A long bearish candle, three small bullish candles staying within its range, then another long bearish candle', 'Five consecutive bullish candles', 'A doji surrounded by two short candles', 'A gap down followed by a gap up'],
      correctIndex: 0,
      explanation: 'The small pullback candles staying contained show the downtrend is only pausing before continuing.',
    ),
    QuizQuestion(
      id: 'medium_11',
      difficulty: 'Medium',
      category: 'Candlestick',
      question: 'A bullish Abandoned Baby pattern features:',
      options: ['A doji that gaps away from both the preceding and following candles', 'Three bullish candles in a row', 'A large bearish candle with no wicks', 'Two identical bullish candles'],
      correctIndex: 0,
      explanation: 'This rare pattern shows a doji isolated by gaps on both sides, signaling a strong reversal.',
    ),
    QuizQuestion(
      id: 'medium_12',
      difficulty: 'Medium',
      category: 'Candlestick',
      question: 'A Three Inside Up pattern confirms a bullish reversal when:',
      options: ['A bullish Harami is followed by a third candle closing above the first candle\'s open', 'A bearish Harami is followed by a lower close', 'Three dojis appear consecutively', 'A single long bearish candle appears'],
      correctIndex: 0,
      explanation: 'The third candle\'s strong close above the first candle\'s open confirms the reversal suggested by the Harami.',
    ),
    QuizQuestion(
      id: 'medium_13',
      difficulty: 'Medium',
      category: 'Candlestick',
      question: 'A Three Inside Down pattern confirms a bearish reversal when:',
      options: ['A bearish Harami is followed by a third candle closing below the first candle\'s open', 'A bullish Harami is followed by a higher close', 'Three dojis appear consecutively', 'A single long bullish candle appears'],
      correctIndex: 0,
      explanation: 'The third candle\'s strong close below the first candle\'s open confirms the reversal suggested by the Harami.',
    ),
    QuizQuestion(
      id: 'medium_14',
      difficulty: 'Medium',
      category: 'Candlestick',
      question: 'A Dragonfly Doji, with a long lower wick and close near the high, typically signals:',
      options: ['A bearish reversal at market tops', 'A possible bullish reversal at market bottoms', 'No significance at all', 'A continuation pattern only'],
      correctIndex: 1,
      explanation: 'The long lower wick shows sellers pushed price down but buyers regained control by the close, hinting at a bottom.',
    ),
    QuizQuestion(
      id: 'medium_15',
      difficulty: 'Medium',
      category: 'Candlestick',
      question: 'A Gravestone Doji, with a long upper wick and close near the low, typically signals:',
      options: ['A possible bearish reversal at market tops', 'A bullish reversal at market bottoms', 'No significance at all', 'A continuation pattern only'],
      correctIndex: 0,
      explanation: 'The long upper wick shows buyers pushed price up but sellers regained control by the close, hinting at a top.',
    ),
    QuizQuestion(
      id: 'medium_16',
      difficulty: 'Medium',
      category: 'Chart Pattern',
      question: 'An Ascending Triangle chart pattern has:',
      options: ['A flat resistance line and a rising support line, often resolving bullishly', 'A flat support line and a falling resistance line', 'Two converging trendlines of equal slope', 'A rounded top and bottom'],
      correctIndex: 0,
      explanation: 'Buyers steadily pushing higher lows against a flat resistance often leads to a bullish breakout.',
    ),
    QuizQuestion(
      id: 'medium_17',
      difficulty: 'Medium',
      category: 'Chart Pattern',
      question: 'A Descending Triangle chart pattern has:',
      options: ['A flat support line and a falling resistance line, often resolving bearishly', 'A flat resistance line and a rising support line', 'Two diverging trendlines', 'A rounded bottom'],
      correctIndex: 0,
      explanation: 'Sellers steadily pushing lower highs against a flat support often leads to a bearish breakdown.',
    ),
    QuizQuestion(
      id: 'medium_18',
      difficulty: 'Medium',
      category: 'Chart Pattern',
      question: 'A Symmetrical Triangle is formed by:',
      options: ['Two converging trendlines of similar slope, with breakout direction determining the bias', 'A single flat trendline', 'Three parallel horizontal lines', 'A widening price channel'],
      correctIndex: 0,
      explanation: 'Symmetrical triangles show contracting volatility; the eventual breakout direction usually signals the next move.',
    ),
    QuizQuestion(
      id: 'medium_19',
      difficulty: 'Medium',
      category: 'Chart Pattern',
      question: 'The Cup and Handle pattern is generally considered:',
      options: ['A bearish reversal pattern', 'A bullish continuation pattern featuring a rounded bottom and small consolidation', 'A pattern only seen in currency pairs', 'A random noise pattern with no meaning'],
      correctIndex: 1,
      explanation: 'The rounded cup followed by a small handle-shaped pullback often precedes a bullish breakout.',
    ),
    QuizQuestion(
      id: 'medium_20',
      difficulty: 'Medium',
      category: 'Chart Pattern',
      question: 'A Bull Flag pattern consists of:',
      options: ['A sharp rally (the pole) followed by a small downward-sloping consolidation channel', 'A sharp decline followed by an upward channel', 'A rounded top formation', 'A single long bearish candle'],
      correctIndex: 0,
      explanation: 'The brief downward consolidation after a strong rally often resolves with continuation of the uptrend.',
    ),
    QuizQuestion(
      id: 'medium_21',
      difficulty: 'Medium',
      category: 'Chart Pattern',
      question: 'A Bear Flag pattern consists of:',
      options: ['A sharp decline (the pole) followed by a small upward-sloping consolidation channel', 'A sharp rally followed by a downward channel', 'A rounded bottom formation', 'A single long bullish candle'],
      correctIndex: 0,
      explanation: 'The brief upward consolidation after a strong decline often resolves with continuation of the downtrend.',
    ),
    QuizQuestion(
      id: 'medium_22',
      difficulty: 'Medium',
      category: 'Chart Pattern',
      question: 'A Pennant pattern differs from a flag mainly because it:',
      options: ['Forms a small symmetrical triangle rather than a parallel channel after a sharp move', 'Only appears on daily charts', 'Has no prior sharp price move', 'Requires five distinct swing points'],
      correctIndex: 0,
      explanation: 'A pennant is a small converging triangle continuation pattern that follows a strong impulsive move.',
    ),
    QuizQuestion(
      id: 'medium_23',
      difficulty: 'Medium',
      category: 'Chart Pattern',
      question: 'A Rising Wedge pattern, with two converging upward-sloping trendlines, is typically considered:',
      options: ['A bullish continuation signal', 'A bearish reversal signal', 'A neutral pattern with no bias', 'Only relevant in commodities'],
      correctIndex: 1,
      explanation: 'Despite the upward slope, rising wedges usually precede a bearish breakdown as momentum weakens.',
    ),
    QuizQuestion(
      id: 'medium_24',
      difficulty: 'Medium',
      category: 'Chart Pattern',
      question: 'A Falling Wedge pattern, with two converging downward-sloping trendlines, is typically considered:',
      options: ['A bearish continuation signal', 'A bullish reversal signal', 'A neutral pattern with no bias', 'Only relevant in indices'],
      correctIndex: 1,
      explanation: 'Despite the downward slope, falling wedges usually precede a bullish breakout as selling momentum weakens.',
    ),
    QuizQuestion(
      id: 'medium_25',
      difficulty: 'Medium',
      category: 'Chart Pattern',
      question: 'A Rectangle chart pattern is characterized by:',
      options: ['Price bouncing between horizontal support and resistance lines', 'Two converging diagonal trendlines', 'A single strong breakout candle', 'A rounded curve shape'],
      correctIndex: 0,
      explanation: 'Price consolidates in a horizontal range until it eventually breaks out in either direction.',
    ),
    QuizQuestion(
      id: 'medium_26',
      difficulty: 'Medium',
      category: 'Chart Pattern',
      question: 'A Broadening Formation (Megaphone pattern) is characterized by:',
      options: ['Diverging trendlines showing increasing volatility and indecision', 'Converging trendlines showing decreasing volatility', 'A flat horizontal channel', 'A single sharp price spike'],
      correctIndex: 0,
      explanation: 'Widening swings between higher highs and lower lows reflect growing uncertainty in the market.',
    ),
    QuizQuestion(
      id: 'medium_27',
      difficulty: 'Medium',
      category: 'Chart Pattern',
      question: 'A Rounding Bottom (Saucer) pattern reflects:',
      options: ['A gradual bearish-to-bullish reversal over an extended period', 'A sudden bullish-to-bearish reversal', 'A sideways range with no bias', 'A single-candle reversal signal'],
      correctIndex: 0,
      explanation: 'The gradual U-shape shows a slow shift from selling pressure to buying pressure.',
    ),
    QuizQuestion(
      id: 'medium_28',
      difficulty: 'Medium',
      category: 'Chart Pattern',
      question: 'A Rounding Top pattern reflects:',
      options: ['A gradual bullish-to-bearish reversal over an extended period', 'A sudden bearish-to-bullish reversal', 'A sideways range with no bias', 'A single-candle reversal signal'],
      correctIndex: 0,
      explanation: 'The gradual dome shape shows a slow shift from buying pressure to selling pressure.',
    ),
    QuizQuestion(
      id: 'medium_29',
      difficulty: 'Medium',
      category: 'Chart Pattern',
      question: 'A Diamond Top pattern is formed by:',
      options: ['A broadening formation that narrows again, typically signaling a bearish reversal at market tops', 'A simple horizontal rectangle', 'A single long wick candle', 'A perfectly symmetrical triangle'],
      correctIndex: 0,
      explanation: 'The diamond shape (widening then narrowing) at a market top often precedes a bearish reversal.',
    ),
    QuizQuestion(
      id: 'medium_30',
      difficulty: 'Medium',
      category: 'Chart Pattern',
      question: 'A Gartley harmonic pattern is used to:',
      options: ['Identify potential reversal zones using specific Fibonacci ratios in an XABCD structure', 'Measure trading volume only', 'Predict news release outcomes', 'Calculate broker spreads'],
      correctIndex: 0,
      explanation: 'Harmonic patterns like the Gartley use precise Fibonacci relationships between price swings to project reversal zones.',
    ),
    QuizQuestion(
      id: 'medium_31',
      difficulty: 'Medium',
      category: 'Indicators',
      question: 'The RSI (Relative Strength Index) is primarily used to measure:',
      options: ['Trading volume', 'Momentum and overbought/oversold conditions', 'Broker spreads', 'Interest rate changes'],
      correctIndex: 1,
      explanation: 'RSI oscillates between 0-100 and commonly uses 70/30 thresholds to flag overbought or oversold conditions.',
    ),
    QuizQuestion(
      id: 'medium_32',
      difficulty: 'Medium',
      category: 'Indicators',
      question: 'The MACD indicator is composed of:',
      options: ['The MACD line, the signal line, and a histogram', 'Only a single moving average', 'Bid and ask price lines', 'Support and resistance zones'],
      correctIndex: 0,
      explanation: 'MACD combines two moving averages (as the MACD line), a signal line, and a histogram showing their difference.',
    ),
    QuizQuestion(
      id: 'medium_33',
      difficulty: 'Medium',
      category: 'Indicators',
      question: 'Bollinger Bands are primarily used to measure:',
      options: ['Volatility, using a moving average with standard deviation bands', 'Trading volume only', 'Interest rate differentials', 'Broker execution speed'],
      correctIndex: 0,
      explanation: 'The bands widen and narrow based on price volatility around a central moving average.',
    ),
    QuizQuestion(
      id: 'medium_34',
      difficulty: 'Medium',
      category: 'Indicators',
      question: 'The Average True Range (ATR) indicator measures:',
      options: ['Market volatility, not direction', 'Trend direction only', 'Support and resistance levels', 'Trading volume'],
      correctIndex: 0,
      explanation: 'ATR quantifies how much price typically moves over a given period, regardless of direction.',
    ),
    QuizQuestion(
      id: 'medium_35',
      difficulty: 'Medium',
      category: 'Indicators',
      question: 'The Stochastic Oscillator compares:',
      options: ['The closing price to the price range over a set period, using 80/20 thresholds', 'Two different currency pairs', 'Broker spread to market spread', 'Volume to open interest'],
      correctIndex: 0,
      explanation: 'Stochastic values above 80 are often considered overbought, and below 20 oversold.',
    ),
    QuizQuestion(
      id: 'medium_36',
      difficulty: 'Medium',
      category: 'Indicators',
      question: 'The ADX (Average Directional Index) primarily measures:',
      options: ['Trend strength, not trend direction', 'The exact price target for a breakout', 'Interest rate expectations', 'Broker commission rates'],
      correctIndex: 0,
      explanation: 'ADX values above 25 typically suggest a strong trend is present, regardless of whether it\'s up or down.',
    ),
    QuizQuestion(
      id: 'medium_37',
      difficulty: 'Medium',
      category: 'Indicators',
      question: 'A Golden Cross occurs when:',
      options: ['A short-term moving average crosses above a long-term moving average, seen as bullish', 'A short-term moving average crosses below a long-term moving average', 'Price crosses above the RSI 70 line', 'Volume spikes above average'],
      correctIndex: 0,
      explanation: 'This crossover (commonly 50-day above 200-day) is widely watched as a bullish trend signal.',
    ),
    QuizQuestion(
      id: 'medium_38',
      difficulty: 'Medium',
      category: 'Indicators',
      question: 'A Death Cross occurs when:',
      options: ['A short-term moving average crosses below a long-term moving average, seen as bearish', 'A short-term moving average crosses above a long-term moving average', 'Price crosses below the RSI 30 line', 'Volume drops to zero'],
      correctIndex: 0,
      explanation: 'This crossover (commonly 50-day below 200-day) is widely watched as a bearish trend signal.',
    ),
    QuizQuestion(
      id: 'medium_39',
      difficulty: 'Medium',
      category: 'Indicators',
      question: 'The Ichimoku Cloud (Kumo) indicator is unique because it:',
      options: ['Shows support/resistance, trend direction, and momentum together in one indicator', 'Only measures trading volume', 'Is exclusively used for cryptocurrency', 'Requires manual daily recalculation'],
      correctIndex: 0,
      explanation: 'Ichimoku combines several components (Tenkan-sen, Kijun-sen, Senkou spans, Chikou span) into a single comprehensive view.',
    ),
    QuizQuestion(
      id: 'medium_40',
      difficulty: 'Medium',
      category: 'Indicators',
      question: 'RSI divergence occurs when:',
      options: ['Price makes a new high or low that the RSI does not confirm, hinting at a potential reversal', 'RSI and price move in perfect sync at all times', 'RSI stays flat for an entire year', 'Price and volume move in opposite directions'],
      correctIndex: 0,
      explanation: 'A mismatch between price extremes and RSI extremes often signals weakening momentum ahead of a reversal.',
    ),
    QuizQuestion(
      id: 'medium_41',
      difficulty: 'Medium',
      category: 'Fibonacci',
      question: 'Common Fibonacci retracement levels used in trading include:',
      options: ['23.6%, 38.2%, 50%, 61.8%, and 78.6%', '10%, 20%, 30%, 40%, and 50%', '25%, 50%, 75%, and 100% only', '33%, 66%, and 99%'],
      correctIndex: 0,
      explanation: 'These ratios derived from the Fibonacci sequence are commonly watched as potential support/resistance zones during pullbacks.',
    ),
    QuizQuestion(
      id: 'medium_42',
      difficulty: 'Medium',
      category: 'Fibonacci',
      question: 'Fibonacci extension levels are primarily used to:',
      options: ['Project potential profit targets beyond the 100% level of a prior move', 'Calculate broker margin requirements', 'Determine the exact time of a reversal', 'Measure trading volume'],
      correctIndex: 0,
      explanation: 'Extensions like 127.2%, 161.8%, and 261.8% help traders estimate how far a move might extend.',
    ),
    QuizQuestion(
      id: 'medium_43',
      difficulty: 'Medium',
      category: 'Chart Pattern',
      question: 'Elliott Wave theory proposes that markets move in:',
      options: ['Five impulse waves followed by three corrective waves', 'Random, unpatterned movements only', 'Two waves total, one up and one down', 'Ten equal waves in every cycle'],
      correctIndex: 0,
      explanation: 'The classic Elliott Wave structure is a 5-wave impulse move followed by a 3-wave corrective move (ABC).',
    ),
    QuizQuestion(
      id: 'medium_44',
      difficulty: 'Medium',
      category: 'Gaps',
      question: 'A breakaway gap typically occurs:',
      options: ['At the start of a new trend, breaking out of a trading range', 'In the middle of an established trend', 'Only at market close on Fridays', 'When a broker changes its spread'],
      correctIndex: 0,
      explanation: 'Breakaway gaps often mark the beginning of a significant new directional move.',
    ),
    QuizQuestion(
      id: 'medium_45',
      difficulty: 'Medium',
      category: 'Gaps',
      question: 'A runaway (measuring) gap typically occurs:',
      options: ['In the middle of an established trend, confirming its continuation', 'At the very start of a trend', 'Only during low volume holidays', 'When a stop out level is reached'],
      correctIndex: 0,
      explanation: 'This gap type confirms strong ongoing momentum partway through an existing trend.',
    ),
    QuizQuestion(
      id: 'medium_46',
      difficulty: 'Medium',
      category: 'Gaps',
      question: 'An exhaustion gap typically occurs:',
      options: ['Near the end of a trend, often signaling a potential reversal', 'At the very beginning of a trend', 'Only in sideways markets', 'Whenever volume is at its lowest'],
      correctIndex: 0,
      explanation: 'This gap type reflects a final burst of buying or selling before the trend runs out of steam.',
    ),
    QuizQuestion(
      id: 'medium_47',
      difficulty: 'Medium',
      category: 'Volume',
      question: 'Volume confirmation in technical analysis means:',
      options: ['Rising price accompanied by rising volume strengthens confidence in the move', 'Volume has no relationship to price validity', 'Falling volume always confirms a breakout', 'Volume only matters on the daily timeframe'],
      correctIndex: 0,
      explanation: 'Strong volume accompanying a price move adds credibility that the move reflects genuine participation.',
    ),
    QuizQuestion(
      id: 'medium_48',
      difficulty: 'Medium',
      category: 'Chart Pattern',
      question: 'Support/resistance role reversal (flip) means:',
      options: ['A broken resistance level often becomes new support, and vice versa', 'Support and resistance never change roles', 'Only round numbers can act as support or resistance', 'Role reversal only applies to indices'],
      correctIndex: 0,
      explanation: 'Once a key level is decisively broken, it frequently switches roles in future price action.',
    ),
    QuizQuestion(
      id: 'medium_49',
      difficulty: 'Medium',
      category: 'Chart Pattern',
      question: 'A trend channel is formed by:',
      options: ['Drawing parallel lines connecting a series of swing highs and swing lows', 'A single horizontal line', 'Random dots on a chart', 'The broker\'s bid-ask spread'],
      correctIndex: 0,
      explanation: 'Channels help visualize the boundaries within which price is trending.',
    ),
    QuizQuestion(
      id: 'medium_50',
      difficulty: 'Medium',
      category: 'Indicators',
      question: 'Pivot points used by day traders are calculated from:',
      options: ['The previous session\'s high, low, and close', 'The current day\'s opening price only', 'The broker\'s commission structure', 'Random Fibonacci numbers'],
      correctIndex: 0,
      explanation: 'Pivot points provide a set of potential intraday support and resistance levels derived from prior session data.',
    ),
  ];

  static List<QuizQuestion> hard = [
    QuizQuestion(
      id: 'hard_1',
      difficulty: 'Hard',
      category: 'Prop Firms & Brokers',
      question: 'The FTMO Challenge evaluation typically consists of how many phases before receiving a funded account?',
      options: ['One phase only', 'Two phases (Challenge and Verification)', 'Four separate phases', 'No phases, funding is instant'],
      correctIndex: 1,
      explanation: 'FTMO\'s standard evaluation path has a Challenge phase followed by a Verification phase before a funded account is granted.',
    ),
    QuizQuestion(
      id: 'hard_2',
      difficulty: 'Hard',
      category: 'Prop Firms & Brokers',
      question: 'On FTMO\'s standard Challenge, what is the typical maximum daily loss limit?',
      options: ['1%', '5%', '20%', 'There is no daily loss limit'],
      correctIndex: 1,
      explanation: 'FTMO\'s standard account rules typically cap daily loss at 5% of the initial account balance.',
    ),
    QuizQuestion(
      id: 'hard_3',
      difficulty: 'Hard',
      category: 'Prop Firms & Brokers',
      question: 'On FTMO\'s standard Challenge, what is the typical maximum overall drawdown limit?',
      options: ['2%', '10%', '50%', 'There is no overall drawdown limit'],
      correctIndex: 1,
      explanation: 'FTMO\'s standard rules typically cap overall (maximum) drawdown at 10% of the initial balance.',
    ),
    QuizQuestion(
      id: 'hard_4',
      difficulty: 'Hard',
      category: 'Prop Firms & Brokers',
      question: 'On FTMO\'s standard Challenge (Phase 1), what is the typical profit target?',
      options: ['1%', '10%', '50%', 'There is no profit target'],
      correctIndex: 1,
      explanation: 'The standard Phase 1 Challenge profit target is typically around 10% of the starting balance.',
    ),
    QuizQuestion(
      id: 'hard_5',
      difficulty: 'Hard',
      category: 'Prop Firms & Brokers',
      question: 'On FTMO\'s Verification (Phase 2), what is the typical profit target?',
      options: ['1%', '5%', '25%', 'There is no profit target in Verification'],
      correctIndex: 1,
      explanation: 'The Verification phase typically requires a lower profit target, around 5%, compared to the initial Challenge.',
    ),
    QuizQuestion(
      id: 'hard_6',
      difficulty: 'Hard',
      category: 'Prop Firms & Brokers',
      question: 'In a prop firm context, what does max drawdown mean?',
      options: ['The maximum allowed decline from the account\'s peak balance or equity', 'The total profit target for the challenge', 'The broker\'s spread on major pairs', 'The number of trades allowed per day'],
      correctIndex: 0,
      explanation: 'Max drawdown rules protect the firm\'s capital by limiting how much a trader\'s equity can fall from its highest point.',
    ),
    QuizQuestion(
      id: 'hard_7',
      difficulty: 'Hard',
      category: 'Prop Firms & Brokers',
      question: 'What is the purpose of a daily loss limit at most prop trading firms?',
      options: ['To prevent excessive losses from occurring within a single trading day', 'To limit the number of winning trades per day', 'To set the broker\'s spread', 'To determine profit split percentages'],
      correctIndex: 0,
      explanation: 'This rule protects both the trader and the firm from a single bad day wiping out the account.',
    ),
    QuizQuestion(
      id: 'hard_8',
      difficulty: 'Hard',
      category: 'Prop Firms & Brokers',
      question: 'Compared to a standard prop firm account, a Swing account typically:',
      options: ['Allows holding trades over the weekend', 'Forbids holding any trades overnight', 'Has no profit target at all', 'Requires a higher minimum deposit'],
      correctIndex: 0,
      explanation: 'Swing accounts are designed for traders who need to hold positions longer, including through weekends.',
    ),
    QuizQuestion(
      id: 'hard_9',
      difficulty: 'Hard',
      category: 'Prop Firms & Brokers',
      question: 'Which of the following is a well-known proprietary trading firm alongside FTMO?',
      options: ['The5%ers', 'Google Finance', 'Bloomberg Terminal', 'MetaQuotes'],
      correctIndex: 0,
      explanation: 'The5%ers is a recognized prop trading firm offering funded account programs similar to FTMO.',
    ),
    QuizQuestion(
      id: 'hard_10',
      difficulty: 'Hard',
      category: 'Prop Firms & Brokers',
      question: 'What is a funded account in the context of proprietary trading firms?',
      options: ['An account where a trader manages the firm\'s capital after passing an evaluation, keeping a share of the profits', 'A personal savings account at a bank', 'A demo account with virtual money only', 'An account that cannot be traded'],
      correctIndex: 0,
      explanation: 'Funded accounts let successful traders trade the firm\'s capital in exchange for a profit split.',
    ),
    QuizQuestion(
      id: 'hard_11',
      difficulty: 'Hard',
      category: 'Prop Firms & Brokers',
      question: 'What is a common profit split percentage offered to traders at many prop firms?',
      options: ['Around 80% to the trader', '100% to the firm only', '10% to the trader', 'There is never a profit split'],
      correctIndex: 0,
      explanation: 'Many prop firms offer traders a large majority share, often around 80% or more, of the profits generated.',
    ),
    QuizQuestion(
      id: 'hard_12',
      difficulty: 'Hard',
      category: 'Prop Firms & Brokers',
      question: 'What does a consistency rule at some prop firms typically require?',
      options: ['No single trading day should represent an excessive percentage of total profits', 'Traders must trade every single day without exception', 'Traders must only use one indicator', 'Traders must risk exactly 50% per trade'],
      correctIndex: 0,
      explanation: 'Consistency rules discourage one lucky day from carrying an entire evaluation, encouraging steady performance.',
    ),
    QuizQuestion(
      id: 'hard_13',
      difficulty: 'Hard',
      category: 'Prop Firms & Brokers',
      question: 'What distinguishes a one-step evaluation from a two-step evaluation at a prop firm?',
      options: ['A one-step model has a single profit target phase, while a two-step model has a Challenge and Verification phase', 'A one-step model requires no profit target at all', 'A two-step model has no drawdown limit', 'There is no real difference between them'],
      correctIndex: 0,
      explanation: 'One-step programs streamline the process into a single evaluation phase, while two-step programs add a Verification phase.',
    ),
    QuizQuestion(
      id: 'hard_14',
      difficulty: 'Hard',
      category: 'Prop Firms & Brokers',
      question: 'At most prop firms, what typically happens if a trader breaches the max daily loss limit?',
      options: ['The evaluation or funded account is usually failed/breached immediately', 'Nothing happens, it is only a warning', 'The trader receives a bonus', 'The profit target is automatically lowered'],
      correctIndex: 0,
      explanation: 'Breaching hard risk rules like the daily loss limit generally results in immediate account failure.',
    ),
    QuizQuestion(
      id: 'hard_15',
      difficulty: 'Hard',
      category: 'Prop Firms & Brokers',
      question: 'Why do prop firms impose strict max drawdown rules on funded traders?',
      options: ['To manage their own risk exposure since they are providing the trading capital', 'To make trading impossible for anyone', 'Because regulators require it for all brokers', 'To reduce their marketing costs'],
      correctIndex: 0,
      explanation: 'Since the firm\'s own capital is at risk, drawdown rules are a core risk management tool.',
    ),
    QuizQuestion(
      id: 'hard_16',
      difficulty: 'Hard',
      category: 'Prop Firms & Brokers',
      question: 'What is a scaling plan offered by some prop firms?',
      options: ['A program that increases a trader\'s funded account size after consistent profitable performance', 'A plan to reduce a trader\'s account size after one loss', 'A tool for calculating pip value', 'A required daily trading schedule'],
      correctIndex: 0,
      explanation: 'Scaling plans reward consistently profitable traders with progressively larger funded accounts.',
    ),
    QuizQuestion(
      id: 'hard_17',
      difficulty: 'Hard',
      category: 'Prop Firms & Brokers',
      question: 'At firms like FTMO, martingale or grid trading strategies are typically:',
      options: ['Restricted or prohibited under the firm\'s trading rules', 'Actively encouraged and rewarded', 'Required for passing the evaluation', 'Irrelevant to the rules'],
      correctIndex: 0,
      explanation: 'High-risk strategies like martingale often conflict with a prop firm\'s risk management requirements and are restricted.',
    ),
    QuizQuestion(
      id: 'hard_18',
      difficulty: 'Hard',
      category: 'Prop Firms & Brokers',
      question: 'What does a news trading restriction at some prop firms typically involve?',
      options: ['Barring traders from opening or holding trades a few minutes around high-impact news releases', 'Requiring traders to trade only during news events', 'Banning all trading permanently', 'Only applying to weekend trading'],
      correctIndex: 0,
      explanation: 'This rule protects against extreme volatility and slippage risk around major news releases.',
    ),
    QuizQuestion(
      id: 'hard_19',
      difficulty: 'Hard',
      category: 'Prop Firms & Brokers',
      question: 'MetaTrader 4 (MT4) is primarily known as:',
      options: ['One of the most widely used retail forex trading platforms', 'A cryptocurrency exchange', 'A prop firm evaluation program', 'A central bank monetary tool'],
      correctIndex: 0,
      explanation: 'MT4 has long been a dominant platform among retail forex traders due to its accessibility and broad broker support.',
    ),
    QuizQuestion(
      id: 'hard_20',
      difficulty: 'Hard',
      category: 'Prop Firms & Brokers',
      question: 'Compared to MT4, MetaTrader 5 (MT5) generally offers:',
      options: ['More timeframes, an integrated economic calendar, and support for more asset classes', 'Fewer timeframes and no economic calendar', 'No support for Expert Advisors', 'Only cryptocurrency trading'],
      correctIndex: 0,
      explanation: 'MT5 expanded on MT4 with additional features, timeframes, and broader multi-asset support.',
    ),
    QuizQuestion(
      id: 'hard_21',
      difficulty: 'Hard',
      category: 'Prop Firms & Brokers',
      question: 'cTrader is popular among traders mainly for offering:',
      options: ['Level II pricing (depth of market) and ECN-style execution', 'Only demo trading capabilities', 'Exclusive access to stock trading', 'Guaranteed profits'],
      correctIndex: 0,
      explanation: 'cTrader\'s market depth visibility and ECN-oriented execution appeal to traders wanting more transparency.',
    ),
    QuizQuestion(
      id: 'hard_22',
      difficulty: 'Hard',
      category: 'Prop Firms & Brokers',
      question: 'What is the main purpose of a demo account?',
      options: ['Practicing trading strategies with virtual funds before risking real money', 'Receiving guaranteed real profits', 'Bypassing broker regulations', 'Avoiding the need for an evaluation'],
      correctIndex: 0,
      explanation: 'Demo accounts let traders test strategies and platforms risk-free using simulated funds.',
    ),
    QuizQuestion(
      id: 'hard_23',
      difficulty: 'Hard',
      category: 'Prop Firms & Brokers',
      question: 'What is slippage in trade execution?',
      options: ['The difference between the expected price of a trade and the price at which it is actually executed', 'The broker\'s monthly account fee', 'The interest paid on overnight positions', 'A type of candlestick pattern'],
      correctIndex: 0,
      explanation: 'Slippage often occurs during fast-moving or low-liquidity market conditions.',
    ),
    QuizQuestion(
      id: 'hard_24',
      difficulty: 'Hard',
      category: 'Prop Firms & Brokers',
      question: 'What is a stop out level set by a broker?',
      options: ['The margin level at which the broker automatically closes open positions to prevent a negative balance', 'The maximum profit a trader is allowed to keep', 'The price level of the previous day\'s close', 'A type of chart pattern'],
      correctIndex: 0,
      explanation: 'When account margin level falls to the stop out threshold, the broker force-closes positions to protect against further losses.',
    ),
    QuizQuestion(
      id: 'hard_25',
      difficulty: 'Hard',
      category: 'Prop Firms & Brokers',
      question: 'What does negative balance protection guarantee for a trader?',
      options: ['That the trader\'s account cannot go below zero, even in extreme market moves', 'That every trade will be profitable', 'That leverage is unlimited', 'That spreads will never widen'],
      correctIndex: 0,
      explanation: 'This broker safeguard prevents traders from owing more money than they deposited.',
    ),
    QuizQuestion(
      id: 'hard_26',
      difficulty: 'Hard',
      category: 'Prop Firms & Brokers',
      question: 'What is the key difference between an ECN broker and a Market Maker broker?',
      options: ['ECN brokers route orders directly to a liquidity pool, while Market Makers may take the other side of a client\'s trade themselves', 'There is no difference, the terms are interchangeable', 'ECN brokers only offer demo accounts', 'Market Makers only trade cryptocurrencies'],
      correctIndex: 0,
      explanation: 'This distinction affects execution model, potential conflicts of interest, and typical spread/commission structures.',
    ),
    QuizQuestion(
      id: 'hard_27',
      difficulty: 'Hard',
      category: 'Prop Firms & Brokers',
      question: 'What is a spread in forex trading?',
      options: ['The difference between the bid and ask price of a currency pair', 'The total leverage offered by a broker', 'The daily profit target of a prop firm', 'A type of candlestick pattern'],
      correctIndex: 0,
      explanation: 'The spread represents a transaction cost built into the difference between buying and selling prices.',
    ),
    QuizQuestion(
      id: 'hard_28',
      difficulty: 'Hard',
      category: 'Prop Firms & Brokers',
      question: 'What is a swap (or rollover) fee in forex trading?',
      options: ['An interest fee charged or credited for holding a position overnight', 'A one-time account opening fee', 'A tax on winning trades only', 'A fee for using a demo account'],
      correctIndex: 0,
      explanation: 'Swap fees reflect the interest rate differential between the two currencies in a pair held overnight.',
    ),
    QuizQuestion(
      id: 'hard_29',
      difficulty: 'Hard',
      category: 'Prop Firms & Brokers',
      question: 'A standard lot in forex trading equals:',
      options: ['1,000 units of the base currency', '10,000 units of the base currency', '100,000 units of the base currency', '1,000,000 units of the base currency'],
      correctIndex: 2,
      explanation: 'A standard lot represents 100,000 units of the base currency, the largest common lot size.',
    ),
    QuizQuestion(
      id: 'hard_30',
      difficulty: 'Hard',
      category: 'Prop Firms & Brokers',
      question: 'A mini lot in forex trading equals:',
      options: ['100,000 units of the base currency', '10,000 units of the base currency', '1,000 units of the base currency', '100 units of the base currency'],
      correctIndex: 1,
      explanation: 'A mini lot represents one-tenth of a standard lot, or 10,000 units of the base currency.',
    ),
    QuizQuestion(
      id: 'hard_31',
      difficulty: 'Hard',
      category: 'Risk Management',
      question: 'What is leverage in trading?',
      options: ['Borrowed capital that allows a trader to control a larger position with a smaller amount of capital', 'A type of candlestick pattern', 'The broker\'s regulatory license number', 'A guaranteed profit mechanism'],
      correctIndex: 0,
      explanation: 'Leverage amplifies both potential gains and potential losses relative to the capital actually deposited.',
    ),
    QuizQuestion(
      id: 'hard_32',
      difficulty: 'Hard',
      category: 'Risk Management',
      question: 'What is a margin call?',
      options: ['A broker\'s warning that account equity has fallen near the required margin level', 'A scheduled call with a financial advisor', 'A bonus payment from the broker', 'A type of chart pattern'],
      correctIndex: 0,
      explanation: 'Margin calls alert traders that their account is at risk of having positions force-closed if losses continue.',
    ),
    QuizQuestion(
      id: 'hard_33',
      difficulty: 'Hard',
      category: 'Risk Management',
      question: 'What risk-reward ratio do many traders commonly aim for at minimum?',
      options: ['1:1', 'At least 1:2 (risking \$1 to potentially make \$2 or more)', '5:1 in the trader\'s disfavor', 'There is no standard guideline at all'],
      correctIndex: 1,
      explanation: 'Targeting a favorable risk-reward ratio helps a strategy remain profitable even with a moderate win rate.',
    ),
    QuizQuestion(
      id: 'hard_34',
      difficulty: 'Hard',
      category: 'Risk Management',
      question: 'What does position sizing refer to?',
      options: ['Determining how many lots or units to trade based on account size and risk tolerance', 'Choosing which broker to use', 'Selecting a chart\'s color scheme', 'Setting the spread on a currency pair'],
      correctIndex: 0,
      explanation: 'Proper position sizing ties trade size directly to a trader\'s account balance and acceptable risk per trade.',
    ),
    QuizQuestion(
      id: 'hard_35',
      difficulty: 'Hard',
      category: 'Risk Management',
      question: 'What does the 1% rule in risk management typically recommend?',
      options: ['Risking no more than 1% of trading capital on a single trade', 'Using 1% leverage at all times', 'Making exactly 1 trade per day', 'Withdrawing 1% of profits weekly'],
      correctIndex: 0,
      explanation: 'This conservative guideline helps traders survive a string of losses without severely damaging their account.',
    ),
    QuizQuestion(
      id: 'hard_36',
      difficulty: 'Hard',
      category: 'Risk Management',
      question: 'What is drawdown in a trading account?',
      options: ['The peak-to-trough decline in account equity over a period', 'The total number of trades placed', 'The broker\'s commission rate', 'A type of candlestick pattern'],
      correctIndex: 0,
      explanation: 'Drawdown quantifies how much an account has fallen from its highest recorded value.',
    ),
    QuizQuestion(
      id: 'hard_37',
      difficulty: 'Hard',
      category: 'Risk Management',
      question: 'What does an R-multiple measure in trading performance?',
      options: ['A trade\'s profit or loss expressed as a multiple of the initial risk taken', 'The number of currency pairs traded', 'The broker\'s regulatory rating', 'The exact time a trade was opened'],
      correctIndex: 0,
      explanation: 'An R-multiple standardizes trade outcomes relative to the amount originally risked, making performance easier to compare.',
    ),
    QuizQuestion(
      id: 'hard_38',
      difficulty: 'Hard',
      category: 'Risk Management',
      question: 'What does expectancy measure in a trading system?',
      options: ['The average amount a trader can expect to win or lose per trade over time', 'The broker\'s spread on a specific pair', 'The exact outcome of the next trade', 'The maximum leverage allowed'],
      correctIndex: 0,
      explanation: 'Expectancy combines win rate and average win/loss size into a single measure of a strategy\'s long-term edge.',
    ),
    QuizQuestion(
      id: 'hard_39',
      difficulty: 'Hard',
      category: 'Risk Management',
      question: 'What does the Sharpe Ratio measure?',
      options: ['Risk-adjusted return relative to volatility', 'The total number of winning trades', 'The broker\'s execution speed', 'The size of a trader\'s account'],
      correctIndex: 0,
      explanation: 'A higher Sharpe Ratio indicates better returns for the amount of risk (volatility) taken on.',
    ),
    QuizQuestion(
      id: 'hard_40',
      difficulty: 'Hard',
      category: 'Risk Management',
      question: 'What is backtesting in trading strategy development?',
      options: ['Testing a trading strategy against historical data to evaluate its performance', 'Trading with real money on a live account only', 'Copying another trader\'s live trades', 'Asking a broker for a rebate'],
      correctIndex: 0,
      explanation: 'Backtesting helps traders evaluate how a strategy would have performed under past market conditions.',
    ),
    QuizQuestion(
      id: 'hard_41',
      difficulty: 'Hard',
      category: 'Risk Management',
      question: 'What is forward testing (or paper trading)?',
      options: ['Testing a strategy in real-time market conditions without risking real capital', 'Testing a strategy only on historical data', 'A method for calculating swap fees', 'A regulatory requirement for all brokers'],
      correctIndex: 0,
      explanation: 'Forward testing validates a strategy\'s performance in live, current market conditions using simulated trades.',
    ),
    QuizQuestion(
      id: 'hard_42',
      difficulty: 'Hard',
      category: 'Risk Management',
      question: 'What is overfitting in strategy development?',
      options: ['Curve-fitting a strategy too closely to historical data so it performs poorly on new data', 'Testing a strategy on too little historical data', 'Using too few indicators in a strategy', 'A type of candlestick pattern'],
      correctIndex: 0,
      explanation: 'An overfit strategy looks great on past data but often fails to generalize to future, unseen market conditions.',
    ),
    QuizQuestion(
      id: 'hard_43',
      difficulty: 'Hard',
      category: 'Risk Management',
      question: 'What is pip value used for?',
      options: ['Calculating the monetary value of a single pip movement for a given position size', 'Determining a broker\'s regulatory license number', 'Measuring account leverage only', 'Setting the spread on a currency pair'],
      correctIndex: 0,
      explanation: 'Pip value lets traders translate price movement directly into profit or loss in their account currency.',
    ),
    QuizQuestion(
      id: 'hard_44',
      difficulty: 'Hard',
      category: 'Risk Management',
      question: 'In most major forex pairs, one pip typically equals:',
      options: ['0.0001 (the fourth decimal place)', '0.01 (the second decimal place)', '1.00 (a whole unit)', '0.1 (the first decimal place)'],
      correctIndex: 0,
      explanation: 'Most major pairs are quoted to four decimal places, with the pip being the fourth decimal.',
    ),
    QuizQuestion(
      id: 'hard_45',
      difficulty: 'Hard',
      category: 'Risk Management',
      question: 'For JPY currency pairs, one pip typically equals:',
      options: ['0.0001 (the fourth decimal place)', '0.01 (the second decimal place)', '1.00 (a whole unit)', '0.001 (the third decimal place)'],
      correctIndex: 1,
      explanation: 'JPY pairs are quoted to two decimal places, making the pip the second decimal place instead of the fourth.',
    ),
    QuizQuestion(
      id: 'hard_46',
      difficulty: 'Hard',
      category: 'Risk Management',
      question: 'What does correlation between currency pairs measure?',
      options: ['A statistical measure of how closely two pairs move in relation to each other', 'The exact profit expected from a trade', 'The broker\'s spread difference', 'The number of pips in a standard lot'],
      correctIndex: 0,
      explanation: 'Understanding correlation helps traders avoid unintentionally doubling up risk on closely related pairs.',
    ),
    QuizQuestion(
      id: 'hard_47',
      difficulty: 'Hard',
      category: 'Risk Management',
      question: 'What is a carry trade strategy?',
      options: ['Borrowing a low-interest-rate currency to buy a higher-interest-rate currency, profiting from the rate differential', 'Buying and selling the same pair simultaneously for no reason', 'A strategy exclusive to cryptocurrency', 'A type of candlestick pattern'],
      correctIndex: 0,
      explanation: 'Carry trades aim to profit from interest rate differentials in addition to any favorable price movement.',
    ),
    QuizQuestion(
      id: 'hard_48',
      difficulty: 'Hard',
      category: 'Risk Management',
      question: 'What does the Kelly Criterion help traders determine?',
      options: ['An optimal position size based on edge and odds to maximize long-term growth', 'The exact entry price for a trade', 'The broker\'s regulatory status', 'The best time of day to trade'],
      correctIndex: 0,
      explanation: 'The Kelly Criterion is a mathematical formula used to size positions in proportion to a strategy\'s statistical edge.',
    ),
    QuizQuestion(
      id: 'hard_49',
      difficulty: 'Hard',
      category: 'Risk Management',
      question: 'What is maximum adverse excursion (MAE) in trade analysis?',
      options: ['The largest unrealized loss a trade experiences before it is closed', 'The total profit of a winning trade', 'The broker\'s maximum leverage offered', 'The number of pips in a spread'],
      correctIndex: 0,
      explanation: 'MAE helps traders analyze how much heat (unrealized drawdown) a trade typically endures before working out.',
    ),
    QuizQuestion(
      id: 'hard_50',
      difficulty: 'Hard',
      category: 'Risk Management',
      question: 'What is a trailing stop?',
      options: ['A stop-loss order that moves with the price to lock in profits as a trade moves favorably', 'A stop-loss that never moves once set', 'An order type only available on demo accounts', 'A fixed take-profit level'],
      correctIndex: 0,
      explanation: 'Trailing stops help protect accumulated profits while still allowing a winning trade room to run.',
    ),
    QuizQuestion(
      id: 'hard_51',
      difficulty: 'Hard',
      category: 'Regulation',
      question: 'Which regulator oversees retail forex brokers in the United States?',
      options: ['The CFTC and NFA', 'The FCA', 'ASIC', 'CySEC'],
      correctIndex: 0,
      explanation: 'In the U.S., the Commodity Futures Trading Commission and National Futures Association regulate forex brokers.',
    ),
    QuizQuestion(
      id: 'hard_52',
      difficulty: 'Hard',
      category: 'Regulation',
      question: 'Which regulator oversees financial firms, including many forex brokers, in the United Kingdom?',
      options: ['The FCA (Financial Conduct Authority)', 'The CFTC', 'ASIC', 'BaFin'],
      correctIndex: 0,
      explanation: 'The FCA is the primary UK regulator overseeing conduct of financial services firms, including forex brokers.',
    ),
    QuizQuestion(
      id: 'hard_53',
      difficulty: 'Hard',
      category: 'Regulation',
      question: 'Which regulator oversees forex brokers in Australia?',
      options: ['ASIC (Australian Securities and Investments Commission)', 'The FCA', 'CySEC', 'The SEC'],
      correctIndex: 0,
      explanation: 'ASIC is Australia\'s main financial regulatory body overseeing broker conduct and licensing.',
    ),
    QuizQuestion(
      id: 'hard_54',
      difficulty: 'Hard',
      category: 'Regulation',
      question: 'Which regulator, commonly used by many EU-facing brokers, is based in Cyprus?',
      options: ['CySEC (Cyprus Securities and Exchange Commission)', 'The FCA', 'ASIC', 'The CFTC'],
      correctIndex: 0,
      explanation: 'CySEC regulates many brokers offering services across the European Union under MiFID passporting rules.',
    ),
    QuizQuestion(
      id: 'hard_55',
      difficulty: 'Hard',
      category: 'Regulation',
      question: 'What is the purpose of segregated client funds at a regulated broker?',
      options: ['To keep client money separate from the broker\'s own operating funds for added protection', 'To increase the broker\'s available leverage', 'To reduce trading spreads', 'To speed up trade execution'],
      correctIndex: 0,
      explanation: 'Segregation helps protect client deposits in the event the broker faces financial difficulties.',
    ),
    QuizQuestion(
      id: 'hard_56',
      difficulty: 'Hard',
      category: 'Regulation',
      question: 'What does STP (Straight Through Processing) mean for a broker\'s execution model?',
      options: ['Orders are passed directly to liquidity providers without dealer intervention', 'Orders are always executed at a fixed price', 'Orders can only be placed on weekends', 'Orders require manual approval from a broker employee'],
      correctIndex: 0,
      explanation: 'STP brokers route client orders automatically to liquidity providers, aiming to reduce conflicts of interest.',
    ),
    QuizQuestion(
      id: 'hard_57',
      difficulty: 'Hard',
      category: 'Regulation',
      question: 'What characterizes a dealing desk broker?',
      options: ['The broker may internally match or take the opposite side of client trades', 'The broker never takes any market risk', 'The broker only offers demo accounts', 'The broker cannot charge any spread'],
      correctIndex: 0,
      explanation: 'Dealing desk (market maker) brokers can act as the counterparty to client trades rather than routing them to the open market.',
    ),
    QuizQuestion(
      id: 'hard_58',
      difficulty: 'Hard',
      category: 'Regulation',
      question: 'What does no dealing desk (NDD) execution mean?',
      options: ['Orders are routed directly to the market or liquidity providers without broker intervention', 'Orders are never actually executed', 'The broker manually approves every trade', 'There is no spread charged at all'],
      correctIndex: 0,
      explanation: 'NDD execution aims to minimize potential conflicts of interest between broker and trader.',
    ),
    QuizQuestion(
      id: 'hard_59',
      difficulty: 'Hard',
      category: 'Regulation',
      question: 'Why is broker regulation generally important for retail traders?',
      options: ['It provides oversight, fund protection measures, and dispute resolution mechanisms', 'It guarantees the trader will always profit', 'It removes all trading risk', 'It eliminates the need for risk management'],
      correctIndex: 0,
      explanation: 'Regulation adds a layer of accountability and recourse that unregulated brokers may not offer.',
    ),
    QuizQuestion(
      id: 'hard_60',
      difficulty: 'Hard',
      category: 'Regulation',
      question: 'What is typically required to verify identity when opening a regulated broker account?',
      options: ['KYC documentation such as government ID and proof of address', 'A trading strategy backtest report', 'A minimum of five years of trading experience', 'Nothing, verification is never required'],
      correctIndex: 0,
      explanation: 'Know Your Customer (KYC) checks are a standard regulatory requirement to prevent fraud and money laundering.',
    ),
    QuizQuestion(
      id: 'hard_61',
      difficulty: 'Hard',
      category: 'Smart Money Concepts',
      question: 'In Smart Money Concepts (SMC), an Order Block refers to:',
      options: ['The last opposing candle before a strong impulsive price move, seen as a potential institutional entry zone', 'A block of time when the market is closed', 'A type of broker fee', 'A candlestick with no wicks'],
      correctIndex: 0,
      explanation: 'Order blocks are viewed as areas where large institutional orders may have been placed, often acting as future support or resistance.',
    ),
    QuizQuestion(
      id: 'hard_62',
      difficulty: 'Hard',
      category: 'Smart Money Concepts',
      question: 'What is a Fair Value Gap (FVG) in SMC terminology?',
      options: ['A price imbalance left between candles where price moved quickly, often expected to be revisited', 'A gap between two brokers\' spreads', 'A required minimum deposit', 'A type of moving average'],
      correctIndex: 0,
      explanation: 'FVGs represent inefficiently traded price zones that price sometimes returns to fill before continuing.',
    ),
    QuizQuestion(
      id: 'hard_63',
      difficulty: 'Hard',
      category: 'Smart Money Concepts',
      question: 'What is a liquidity sweep (or stop hunt) in trading?',
      options: ['Price briefly moving beyond a key high or low to trigger stop orders before reversing', 'A broker sweeping unused margin into a savings account', 'A type of scheduled news event', 'A candlestick pattern with three components'],
      correctIndex: 0,
      explanation: 'Liquidity sweeps are thought to clear out stop-loss clusters before the \'real\' move develops in the opposite direction.',
    ),
    QuizQuestion(
      id: 'hard_64',
      difficulty: 'Hard',
      category: 'Smart Money Concepts',
      question: 'What is a breaker block in SMC terminology?',
      options: ['A former order block that failed and now acts as support or resistance in the opposite direction', 'A type of broker execution error', 'A permanently unbreakable support level', 'A candlestick with equal wicks'],
      correctIndex: 0,
      explanation: 'When an order block fails to hold, it can flip roles and act as a new zone of interest in the opposite direction.',
    ),
    QuizQuestion(
      id: 'hard_65',
      difficulty: 'Hard',
      category: 'Smart Money Concepts',
      question: 'What does a market structure break (MSB or BOS) indicate?',
      options: ['A shift in trend direction confirmed by price breaking a prior significant swing high or low', 'A broker system outage', 'A change in a currency pair\'s spread', 'A required trading pause'],
      correctIndex: 0,
      explanation: 'Breaking key structural points is commonly used to confirm that a trend has changed direction.',
    ),
    QuizQuestion(
      id: 'hard_66',
      difficulty: 'Hard',
      category: 'Smart Money Concepts',
      question: 'What is inducement in SMC terminology?',
      options: ['A price move designed to lure retail traders into a position before the real institutional move happens', 'A bonus offered by a prop firm', 'A type of stop-loss order', 'A required margin deposit'],
      correctIndex: 0,
      explanation: 'Inducement describes price action that traps traders on the wrong side before a larger move unfolds.',
    ),
    QuizQuestion(
      id: 'hard_67',
      difficulty: 'Hard',
      category: 'Smart Money Concepts',
      question: 'What is a premium zone in SMC terminology?',
      options: ['An area above the midpoint of a price range considered relatively expensive for buying', 'An area with the lowest recorded price ever', 'A broker\'s premium account tier', 'A candlestick with a long lower wick'],
      correctIndex: 0,
      explanation: 'Traders often look to sell (or avoid buying) within premium zones of an established price range.',
    ),
    QuizQuestion(
      id: 'hard_68',
      difficulty: 'Hard',
      category: 'Smart Money Concepts',
      question: 'What is a discount zone in SMC terminology?',
      options: ['An area below the midpoint of a price range considered relatively cheap for buying', 'An area with the highest recorded price ever', 'A broker\'s discounted commission tier', 'A candlestick with a long upper wick'],
      correctIndex: 0,
      explanation: 'Traders often look to buy within discount zones of an established price range.',
    ),
    QuizQuestion(
      id: 'hard_69',
      difficulty: 'Hard',
      category: 'Smart Money Concepts',
      question: 'The Wyckoff Method divides market cycles into which four phases?',
      options: ['Accumulation, Markup, Distribution, and Markdown', 'Opening, Midday, Closing, and Overnight', 'Bullish, Bearish, Neutral, and Volatile', 'Support, Resistance, Breakout, and Retest'],
      correctIndex: 0,
      explanation: 'Wyckoff\'s model describes how smart money accumulates positions, marks price up, distributes positions, then marks price down.',
    ),
    QuizQuestion(
      id: 'hard_70',
      difficulty: 'Hard',
      category: 'Smart Money Concepts',
      question: 'In Wyckoff theory, what does a Spring refer to?',
      options: ['A brief false breakdown below support designed to shake out weak holders before a rally', 'A sudden interest rate hike', 'A type of candlestick with no wicks', 'A broker\'s minimum lot size'],
      correctIndex: 0,
      explanation: 'Springs are viewed as a final shakeout of sellers before smart money drives price higher during accumulation.',
    ),
    QuizQuestion(
      id: 'hard_71',
      difficulty: 'Hard',
      category: 'Smart Money Concepts',
      question: 'In Wyckoff theory, what does an Upthrust refer to?',
      options: ['A brief false breakout above resistance before a decline', 'A sustained strong uptrend', 'A type of moving average', 'A broker\'s margin requirement'],
      correctIndex: 0,
      explanation: 'Upthrusts are viewed as a final trap of buyers before smart money drives price lower during distribution.',
    ),
    QuizQuestion(
      id: 'hard_72',
      difficulty: 'Hard',
      category: 'Smart Money Concepts',
      question: 'In Wyckoff analysis, what does accumulation describe?',
      options: ['A phase where smart money quietly builds long positions before a markup phase', 'A phase where all traders are selling aggressively', 'A single candlestick pattern', 'A broker\'s fee schedule'],
      correctIndex: 0,
      explanation: 'Accumulation typically occurs in a range after a downtrend, as informed participants build positions.',
    ),
    QuizQuestion(
      id: 'hard_73',
      difficulty: 'Hard',
      category: 'Smart Money Concepts',
      question: 'In Wyckoff analysis, what does distribution describe?',
      options: ['A phase where smart money offloads positions before a markdown phase', 'A phase where smart money is aggressively buying', 'A single candlestick pattern', 'A broker\'s regulatory filing'],
      correctIndex: 0,
      explanation: 'Distribution typically occurs in a range after an uptrend, as informed participants sell into strength.',
    ),
    QuizQuestion(
      id: 'hard_74',
      difficulty: 'Hard',
      category: 'Smart Money Concepts',
      question: 'What does VWAP stand for?',
      options: ['Volume Weighted Average Price', 'Variable Weekly Average Price', 'Value Weighted Asset Position', 'Volatility Weighted Average Percentage'],
      correctIndex: 0,
      explanation: 'VWAP calculates the average price of an asset weighted by the volume traded at each price level.',
    ),
    QuizQuestion(
      id: 'hard_75',
      difficulty: 'Hard',
      category: 'Smart Money Concepts',
      question: 'VWAP is commonly used by traders to:',
      options: ['Identify a volume-weighted fair value benchmark for the trading session', 'Calculate a broker\'s spread', 'Predict upcoming news releases', 'Set the maximum leverage allowed'],
      correctIndex: 0,
      explanation: 'Many institutional traders use VWAP as a reference point for whether current price is relatively cheap or expensive.',
    ),
    QuizQuestion(
      id: 'hard_76',
      difficulty: 'Hard',
      category: 'Smart Money Concepts',
      question: 'What is delta volume in order flow trading?',
      options: ['The difference between aggressive buying volume and aggressive selling volume', 'The total number of trades placed in a day', 'The broker\'s commission per lot', 'A type of candlestick wick'],
      correctIndex: 0,
      explanation: 'Delta volume helps traders gauge which side (buyers or sellers) is more aggressive at a given moment.',
    ),
    QuizQuestion(
      id: 'hard_77',
      difficulty: 'Hard',
      category: 'Smart Money Concepts',
      question: 'What is a footprint chart?',
      options: ['A chart showing detailed buy and sell volume at each price level within a candle', 'A chart showing only closing prices', 'A chart used exclusively for stock indices', 'A chart that hides all volume data'],
      correctIndex: 0,
      explanation: 'Footprint charts give a granular view of order flow activity inside each candle or bar.',
    ),
    QuizQuestion(
      id: 'hard_78',
      difficulty: 'Hard',
      category: 'Smart Money Concepts',
      question: 'What does high open interest in futures or options markets generally indicate?',
      options: ['A large number of outstanding contracts, reflecting significant market participation', 'That the market is about to close permanently', 'That the broker has gone bankrupt', 'That no traders are active'],
      correctIndex: 0,
      explanation: 'Rising open interest alongside price movement is often used to gauge the strength of a trend.',
    ),
    QuizQuestion(
      id: 'hard_79',
      difficulty: 'Hard',
      category: 'Smart Money Concepts',
      question: 'What is a supply and demand zone in trading?',
      options: ['A price area where past strong buying (demand) or selling (supply) caused a significant price move', 'A government-mandated trading boundary', 'A type of broker fee structure', 'A fixed daily trading session time'],
      correctIndex: 0,
      explanation: 'These zones are watched for potential reactions if price returns to them in the future.',
    ),
    QuizQuestion(
      id: 'hard_80',
      difficulty: 'Hard',
      category: 'Smart Money Concepts',
      question: 'What does mitigation mean in SMC terminology?',
      options: ['Price returning to an order block or imbalance to be partially or fully filled before continuing', 'A broker reducing a trader\'s leverage', 'A type of stop-loss placement rule', 'A required daily loss report'],
      correctIndex: 0,
      explanation: 'Mitigation describes price revisiting an earlier inefficient zone before the underlying trend resumes.',
    ),
    QuizQuestion(
      id: 'hard_81',
      difficulty: 'Hard',
      category: 'Macro & Fundamentals',
      question: 'What does Non-Farm Payrolls (NFP) measure?',
      options: ['The change in the number of employed people in the U.S., excluding farm workers', 'The total value of U.S. exports', 'The U.S. central bank\'s interest rate decision', 'The U.S. government\'s total debt level'],
      correctIndex: 0,
      explanation: 'NFP is a closely watched monthly U.S. economic report that can cause significant forex volatility.',
    ),
    QuizQuestion(
      id: 'hard_82',
      difficulty: 'Hard',
      category: 'Macro & Fundamentals',
      question: 'What does CPI stand for and measure?',
      options: ['Consumer Price Index, a measure of inflation', 'Capital Profit Indicator, a measure of broker earnings', 'Currency Parity Index, a measure of exchange rates', 'Central Policy Interest, a measure of interest rates'],
      correctIndex: 0,
      explanation: 'CPI tracks changes in the price of a basket of goods and services, serving as a key inflation gauge.',
    ),
    QuizQuestion(
      id: 'hard_83',
      difficulty: 'Hard',
      category: 'Macro & Fundamentals',
      question: 'What is quantitative easing (QE)?',
      options: ['A central bank policy of buying assets to increase money supply and stimulate the economy', 'A tax policy that reduces government spending', 'A broker\'s method for calculating spreads', 'A type of chart pattern'],
      correctIndex: 0,
      explanation: 'QE is an unconventional monetary policy tool typically used when interest rates are already near zero.',
    ),
    QuizQuestion(
      id: 'hard_84',
      difficulty: 'Hard',
      category: 'Macro & Fundamentals',
      question: 'How does raising interest rates typically affect a currency\'s value?',
      options: ['It tends to strengthen the currency due to higher yield attractiveness to investors', 'It always weakens the currency instantly', 'It has no effect on currency value', 'It only affects stock prices, not currencies'],
      correctIndex: 0,
      explanation: 'Higher rates often attract foreign capital seeking better returns, increasing demand for that currency.',
    ),
    QuizQuestion(
      id: 'hard_85',
      difficulty: 'Hard',
      category: 'Macro & Fundamentals',
      question: 'What is the Commitments of Traders (COT) report used for?',
      options: ['Showing the positioning of different trader categories, such as commercial and non-commercial, in futures markets', 'Reporting a broker\'s daily revenue', 'Listing upcoming holidays for the forex market', 'Displaying real-time bid/ask spreads'],
      correctIndex: 0,
      explanation: 'The COT report, released weekly by the CFTC, offers insight into how large players are positioned in futures markets.',
    ),
    QuizQuestion(
      id: 'hard_86',
      difficulty: 'Hard',
      category: 'Macro & Fundamentals',
      question: 'What does interest rate differential refer to in forex trading?',
      options: ['The difference in interest rates between two countries\' currencies, influencing carry trade flows', 'The difference between a broker\'s bid and ask price', 'The total leverage offered on an account', 'The number of pips in a standard lot'],
      correctIndex: 0,
      explanation: 'A wider interest rate differential can make carry trade strategies between two currencies more attractive.',
    ),
    QuizQuestion(
      id: 'hard_87',
      difficulty: 'Hard',
      category: 'Macro & Fundamentals',
      question: 'Which entity is responsible for setting U.S. monetary policy?',
      options: ['The Federal Reserve (Fed)', 'The CFTC', 'The NFA', 'The U.S. Treasury alone'],
      correctIndex: 0,
      explanation: 'The Federal Reserve sets key interest rates and conducts monetary policy for the United States.',
    ),
    QuizQuestion(
      id: 'hard_88',
      difficulty: 'Hard',
      category: 'Macro & Fundamentals',
      question: 'What is meant by safe-haven currency behavior?',
      options: ['Certain currencies, like the USD, JPY, or CHF, tend to strengthen during times of market uncertainty', 'All currencies behave identically during a crisis', 'Only cryptocurrencies act as safe havens', 'Safe-haven currencies always weaken during uncertainty'],
      correctIndex: 0,
      explanation: 'Investors often flock to perceived safe-haven currencies when risk appetite falls during turmoil.',
    ),
    QuizQuestion(
      id: 'hard_89',
      difficulty: 'Hard',
      category: 'Macro & Fundamentals',
      question: 'What does GDP measure?',
      options: ['The total value of goods and services produced in an economy over a period', 'The total debt held by a government', 'The daily trading volume of a currency pair', 'A central bank\'s gold reserves'],
      correctIndex: 0,
      explanation: 'GDP is one of the broadest indicators used to gauge overall economic health and growth.',
    ),
    QuizQuestion(
      id: 'hard_90',
      difficulty: 'Hard',
      category: 'Macro & Fundamentals',
      question: 'What is a central bank intervention in forex markets?',
      options: ['Direct action by a central bank to influence its currency\'s value, such as buying or selling in the open market', 'A broker halting trading temporarily', 'A scheduled economic data release', 'A type of chart pattern'],
      correctIndex: 0,
      explanation: 'Central banks sometimes intervene directly to counter excessive currency strength or weakness.',
    ),
    QuizQuestion(
      id: 'hard_91',
      difficulty: 'Hard',
      category: 'Advanced Markets',
      question: 'What is implied volatility in options trading?',
      options: ['The market\'s forecast of a likely price movement, derived from current option prices', 'The historical average price of an asset', 'A fixed constant set by regulators', 'The broker\'s spread on options contracts'],
      correctIndex: 0,
      explanation: 'Implied volatility reflects how much price movement the market expects going forward, based on options pricing.',
    ),
    QuizQuestion(
      id: 'hard_92',
      difficulty: 'Hard',
      category: 'Advanced Markets',
      question: 'What does gamma exposure refer to in options markets?',
      options: ['The rate of change of an option\'s delta relative to price movement, influencing dealer hedging flows', 'The total number of options contracts traded in a day', 'A broker\'s regulatory license number', 'The interest rate on a margin account'],
      correctIndex: 0,
      explanation: 'Large gamma exposure among dealers can amplify or dampen price moves as they hedge their positions.',
    ),
    QuizQuestion(
      id: 'hard_93',
      difficulty: 'Hard',
      category: 'Advanced Markets',
      question: 'What is a funding rate in perpetual futures (common in crypto markets)?',
      options: ['A periodic payment between long and short traders to keep the perpetual contract price close to spot price', 'A one-time fee for opening any futures account', 'A tax imposed by regulators on all trades', 'A fixed daily broker commission'],
      correctIndex: 0,
      explanation: 'Funding rates incentivize the perpetual futures price to stay anchored near the underlying spot price.',
    ),
    QuizQuestion(
      id: 'hard_94',
      difficulty: 'Hard',
      category: 'Advanced Markets',
      question: 'What is open interest in options or futures markets?',
      options: ['The total number of outstanding contracts that have not yet been settled or closed', 'The total trading volume for a single day only', 'The broker\'s available margin', 'A type of candlestick pattern'],
      correctIndex: 0,
      explanation: 'Open interest reflects how many contracts remain active, offering insight into market participation and conviction.',
    ),
    QuizQuestion(
      id: 'hard_95',
      difficulty: 'Hard',
      category: 'Advanced Markets',
      question: 'What is a dark pool?',
      options: ['A private trading venue where large orders are executed without public pre-trade transparency', 'A publicly listed stock exchange', 'A type of central bank reserve', 'A candlestick with a long lower wick'],
      correctIndex: 0,
      explanation: 'Dark pools allow institutions to trade large blocks with reduced market impact by keeping orders hidden pre-trade.',
    ),
    QuizQuestion(
      id: 'hard_96',
      difficulty: 'Hard',
      category: 'Advanced Markets',
      question: 'Order flow trading is primarily based on analyzing:',
      options: ['Real-time buy and sell order data to gauge market sentiment and imbalance', 'Only historical daily closing prices', 'A broker\'s marketing materials', 'Government tax policy changes'],
      correctIndex: 0,
      explanation: 'Order flow traders study live transactional data to anticipate short-term price movement.',
    ),
    QuizQuestion(
      id: 'hard_97',
      difficulty: 'Hard',
      category: 'Advanced Markets',
      question: 'What does market depth (Level II data) show a trader?',
      options: ['The list of buy and sell orders at different price levels for an instrument', 'The broker\'s regulatory status', 'A summary of monthly economic data', 'The historical performance of a strategy'],
      correctIndex: 0,
      explanation: 'Level II data reveals the order book, showing where liquidity is resting above and below the current price.',
    ),
    QuizQuestion(
      id: 'hard_98',
      difficulty: 'Hard',
      category: 'Advanced Markets',
      question: 'What is a limit order?',
      options: ['An order to buy or sell at a specified price or better', 'An order that is always executed instantly at the current market price', 'An order that can never be cancelled', 'A type of candlestick pattern'],
      correctIndex: 0,
      explanation: 'Limit orders give traders control over the exact price at which they are willing to transact.',
    ),
    QuizQuestion(
      id: 'hard_99',
      difficulty: 'Hard',
      category: 'Advanced Markets',
      question: 'What is a market order?',
      options: ['An order executed immediately at the best available current price', 'An order that waits for a specific price to be reached', 'An order only available on demo accounts', 'A type of chart pattern'],
      correctIndex: 0,
      explanation: 'Market orders prioritize immediate execution over price certainty.',
    ),
    QuizQuestion(
      id: 'hard_100',
      difficulty: 'Hard',
      category: 'Advanced Markets',
      question: 'What is algorithmic trading (often implemented as an EA in MT4/MT5)?',
      options: ['Automated trading using pre-programmed rules to execute trades without manual intervention', 'Trading based purely on gut feeling', 'A type of candlestick pattern', 'A regulatory filing requirement'],
      correctIndex: 0,
      explanation: 'Expert Advisors and other algorithmic systems execute trades automatically based on coded strategy logic.',
    ),
  ];

  static List<QuizQuestion> all = [...easy, ...medium, ...hard];
}

