import 'models.dart';

class SampleData {
  static List<ForexPair> pairs = [
    // FOREX
    ForexPair(pair: 'EUR/USD',
        flag: '🇪🇺🇺🇸',
        price: 1.0847,
        change: 0.0023,
        changePct: 0.21,
        isUp: true,
        category: 'Forex',
        spark: [
          1.080,
          1.081,
          1.082,
          1.081,
          1.083,
          1.082,
          1.084,
          1.083,
          1.085,
          1.0847
        ]),
    ForexPair(pair: 'GBP/USD',
        flag: '🇬🇧🇺🇸',
        price: 1.2734,
        change: -0.0010,
        changePct: -0.08,
        isUp: false,
        category: 'Forex',
        spark: [
          1.276,
          1.275,
          1.274,
          1.275,
          1.273,
          1.274,
          1.272,
          1.273,
          1.272,
          1.2734
        ]),
    ForexPair(pair: 'USD/JPY',
        flag: '🇺🇸🇯🇵',
        price: 157.42,
        change: 0.53,
        changePct: 0.34,
        isUp: true,
        category: 'Forex',
        spark: [
          156.8,
          156.9,
          157.1,
          157.0,
          157.2,
          157.1,
          157.3,
          157.2,
          157.4,
          157.42
        ]),
    ForexPair(pair: 'AUD/USD',
        flag: '🇦🇺🇺🇸',
        price: 0.6582,
        change: 0.0008,
        changePct: 0.12,
        isUp: true,
        category: 'Forex',
        spark: [
          0.656,
          0.657,
          0.657,
          0.658,
          0.657,
          0.658,
          0.659,
          0.658,
          0.659,
          0.6582
        ]),
    ForexPair(pair: 'USD/CAD',
        flag: '🇺🇸🇨🇦',
        price: 1.3641,
        change: -0.0021,
        changePct: -0.15,
        isUp: false,
        category: 'Forex',
        spark: [
          1.367,
          1.366,
          1.366,
          1.365,
          1.366,
          1.365,
          1.364,
          1.365,
          1.364,
          1.3641
        ]),
    ForexPair(pair: 'USD/CHF',
        flag: '🇺🇸🇨🇭',
        price: 0.8978,
        change: 0.0008,
        changePct: 0.09,
        isUp: true,
        category: 'Forex',
        spark: [
          0.895,
          0.896,
          0.896,
          0.897,
          0.896,
          0.897,
          0.897,
          0.898,
          0.897,
          0.8978
        ]),
    ForexPair(pair: 'NZD/USD',
        flag: '🇳🇿🇺🇸',
        price: 0.6081,
        change: -0.0013,
        changePct: -0.22,
        isUp: false,
        category: 'Forex',
        spark: [
          0.611,
          0.610,
          0.610,
          0.609,
          0.609,
          0.608,
          0.609,
          0.608,
          0.608,
          0.6081
        ]),
    ForexPair(pair: 'EUR/GBP',
        flag: '🇪🇺🇬🇧',
        price: 0.8519,
        change: 0.0005,
        changePct: 0.06,
        isUp: true,
        category: 'Forex',
        spark: [
          0.850,
          0.851,
          0.851,
          0.852,
          0.851,
          0.852,
          0.852,
          0.852,
          0.852,
          0.8519
        ]),
    ForexPair(pair: 'USD/TRY',
        flag: '🇺🇸🇹🇷',
        price: 32.14,
        change: 0.21,
        changePct: 0.66,
        isUp: true,
        category: 'Forex',
        spark: [
          31.8,
          31.9,
          31.95,
          32.0,
          32.05,
          32.1,
          32.1,
          32.12,
          32.13,
          32.14
        ]),
    ForexPair(pair: 'USD/ZAR',
        flag: '🇺🇸🇿🇦',
        price: 18.42,
        change: -0.14,
        changePct: -0.75,
        isUp: false,
        category: 'Forex',
        spark: [
          18.6,
          18.58,
          18.55,
          18.53,
          18.51,
          18.50,
          18.48,
          18.46,
          18.44,
          18.42
        ]),
    // INDICES
    ForexPair(pair: 'S&P 500',
        flag: '📈🇺🇸',
        price: 5487.30,
        change: 23.40,
        changePct: 0.43,
        isUp: true,
        category: 'Indices',
        spark: [5460, 5465, 5462, 5470, 5468, 5475, 5472, 5480, 5484, 5487.30]),
    ForexPair(pair: 'NASDAQ',
        flag: '💻🇺🇸',
        price: 17832.0,
        change: -45.20,
        changePct: -0.25,
        isUp: false,
        category: 'Indices',
        spark: [
          17900,
          17880,
          17870,
          17860,
          17850,
          17848,
          17845,
          17840,
          17836,
          17832
        ]),
    ForexPair(pair: 'DOW JONES',
        flag: '🏦🇺🇸',
        price: 39214.0,
        change: 112.0,
        changePct: 0.29,
        isUp: true,
        category: 'Indices',
        spark: [
          39080,
          39100,
          39095,
          39120,
          39115,
          39150,
          39160,
          39190,
          39205,
          39214
        ]),
    ForexPair(pair: 'FTSE 100',
        flag: '📊🇬🇧',
        price: 8245.60,
        change: -18.30,
        changePct: -0.22,
        isUp: false,
        category: 'Indices',
        spark: [8270, 8265, 8260, 8258, 8255, 8252, 8250, 8248, 8247, 8245.60]),
    ForexPair(pair: 'DAX 40',
        flag: '🇩🇪📈',
        price: 18654.0,
        change: 78.50,
        changePct: 0.42,
        isUp: true,
        category: 'Indices',
        spark: [
          18560,
          18575,
          18580,
          18595,
          18600,
          18615,
          18625,
          18635,
          18645,
          18654
        ]),
    ForexPair(pair: 'NIKKEI',
        flag: '🇯🇵📊',
        price: 38920.0,
        change: -210.0,
        changePct: -0.54,
        isUp: false,
        category: 'Indices',
        spark: [
          39150,
          39100,
          39050,
          39000,
          38990,
          38970,
          38960,
          38950,
          38935,
          38920
        ]),
    ForexPair(pair: 'CAC 40',
        flag: '🇫🇷📈',
        price: 7842.30,
        change: 34.20,
        changePct: 0.44,
        isUp: true,
        category: 'Indices',
        spark: [7800, 7808, 7812, 7820, 7825, 7830, 7834, 7838, 7840, 7842.30]),
    ForexPair(pair: 'HANG SENG',
        flag: '🇭🇰📊',
        price: 18124.0,
        change: -98.0,
        changePct: -0.54,
        isUp: false,
        category: 'Indices',
        spark: [
          18300,
          18280,
          18260,
          18240,
          18220,
          18200,
          18180,
          18160,
          18140,
          18124
        ]),
    ForexPair(pair: 'ASX 200',
        flag: '🇦🇺📈',
        price: 7634.50,
        change: 22.80,
        changePct: 0.30,
        isUp: true,
        category: 'Indices',
        spark: [7605, 7610, 7612, 7616, 7618, 7622, 7625, 7628, 7631, 7634.50]),
    ForexPair(pair: 'VIX',
        flag: '😨📉',
        price: 13.42,
        change: -0.84,
        changePct: -5.89,
        isUp: false,
        category: 'Indices',
        spark: [14.5, 14.3, 14.1, 13.9, 13.8, 13.7, 13.6, 13.55, 13.5, 13.42]),
    // STOCKS
    ForexPair(pair: 'AAPL',
        flag: '🍎🇺🇸',
        price: 213.42,
        change: 3.21,
        changePct: 1.53,
        isUp: true,
        category: 'Stocks',
        spark: [208, 209, 210, 209, 211, 210, 212, 211, 213, 213.42]),
    ForexPair(pair: 'TSLA',
        flag: '🚗🇺🇸',
        price: 248.75,
        change: -6.30,
        changePct: -2.47,
        isUp: false,
        category: 'Stocks',
        spark: [258, 256, 254, 253, 252, 251, 250, 249, 249, 248.75]),
    ForexPair(pair: 'NVDA',
        flag: '🖥️🇺🇸',
        price: 875.60,
        change: 24.80,
        changePct: 2.91,
        isUp: true,
        category: 'Stocks',
        spark: [845, 850, 852, 858, 860, 862, 865, 868, 872, 875.60]),
    ForexPair(pair: 'GOOGL',
        flag: '🔍🇺🇸',
        price: 178.34,
        change: 1.45,
        changePct: 0.82,
        isUp: true,
        category: 'Stocks',
        spark: [175, 176, 176, 177, 177, 177, 178, 178, 178, 178.34]),
    ForexPair(pair: 'MSFT',
        flag: '🪟🇺🇸',
        price: 432.18,
        change: -2.30,
        changePct: -0.53,
        isUp: false,
        category: 'Stocks',
        spark: [436, 435, 434, 434, 433, 433, 432, 432, 432, 432.18]),
    ForexPair(pair: 'AMZN',
        flag: '📦🇺🇸',
        price: 192.40,
        change: 4.60,
        changePct: 2.45,
        isUp: true,
        category: 'Stocks',
        spark: [186, 187, 188, 189, 189, 190, 191, 191, 192, 192.40]),
    ForexPair(pair: 'META',
        flag: '🌐🇺🇸',
        price: 524.80,
        change: 8.40,
        changePct: 1.63,
        isUp: true,
        category: 'Stocks',
        spark: [512, 514, 516, 518, 519, 520, 521, 522, 524, 524.80]),
    ForexPair(pair: 'BABA',
        flag: '🛒🇨🇳',
        price: 82.14,
        change: -1.24,
        changePct: -1.49,
        isUp: false,
        category: 'Stocks',
        spark: [84, 83.5, 83, 82.8, 82.6, 82.5, 82.4, 82.3, 82.2, 82.14]),
    ForexPair(pair: 'NFLX',
        flag: '🎬🇺🇸',
        price: 684.20,
        change: 12.40,
        changePct: 1.85,
        isUp: true,
        category: 'Stocks',
        spark: [668, 670, 672, 674, 676, 678, 680, 681, 683, 684.20]),
    ForexPair(pair: 'JPM',
        flag: '🏦🇺🇸',
        price: 198.34,
        change: -1.80,
        changePct: -0.90,
        isUp: false,
        category: 'Stocks',
        spark: [201, 200, 199, 199, 199, 198, 198, 198, 198, 198.34]),
    // CRYPTO
    ForexPair(pair: 'BTC/USD',
        flag: '₿🟡',
        price: 68241.0,
        change: 1240.0,
        changePct: 1.85,
        isUp: true,
        category: 'Crypto',
        spark: [
          66800,
          67100,
          67000,
          67400,
          67600,
          67800,
          68000,
          68100,
          68200,
          68241
        ]),
    ForexPair(pair: 'ETH/USD',
        flag: '⟠🔵',
        price: 3842.50,
        change: -87.30,
        changePct: -2.22,
        isUp: false,
        category: 'Crypto',
        spark: [3950, 3930, 3920, 3910, 3900, 3890, 3870, 3860, 3850, 3842.50]),
    ForexPair(pair: 'BNB/USD',
        flag: '🔶🟡',
        price: 612.30,
        change: 8.40,
        changePct: 1.39,
        isUp: true,
        category: 'Crypto',
        spark: [600, 602, 603, 605, 606, 608, 609, 610, 611, 612.30]),
    ForexPair(pair: 'SOL/USD',
        flag: '🌐🔵',
        price: 178.60,
        change: 5.20,
        changePct: 3.00,
        isUp: true,
        category: 'Crypto',
        spark: [170, 172, 173, 174, 175, 175, 176, 177, 178, 178.60]),
    ForexPair(pair: 'XRP/USD',
        flag: '💧🔵',
        price: 0.5842,
        change: -0.012,
        changePct: -2.01,
        isUp: false,
        category: 'Crypto',
        spark: [
          0.600,
          0.598,
          0.596,
          0.594,
          0.592,
          0.590,
          0.588,
          0.587,
          0.585,
          0.5842
        ]),
    ForexPair(pair: 'ADA/USD',
        flag: '🔷🔵',
        price: 0.4521,
        change: 0.0082,
        changePct: 1.85,
        isUp: true,
        category: 'Crypto',
        spark: [
          0.440,
          0.442,
          0.444,
          0.446,
          0.447,
          0.448,
          0.449,
          0.450,
          0.451,
          0.4521
        ]),
    ForexPair(pair: 'DOGE',
        flag: '🐕🟡',
        price: 0.1624,
        change: 0.0044,
        changePct: 2.79,
        isUp: true,
        category: 'Crypto',
        spark: [
          0.155,
          0.157,
          0.158,
          0.159,
          0.160,
          0.161,
          0.161,
          0.162,
          0.162,
          0.1624
        ]),
    ForexPair(pair: 'AVAX',
        flag: '🔺🔴',
        price: 38.42,
        change: -1.24,
        changePct: -3.13,
        isUp: false,
        category: 'Crypto',
        spark: [40.5, 40.2, 39.8, 39.5, 39.2, 39.0, 38.8, 38.6, 38.5, 38.42]),
    ForexPair(pair: 'LINK',
        flag: '⛓️🔵',
        price: 14.82,
        change: 0.42,
        changePct: 2.92,
        isUp: true,
        category: 'Crypto',
        spark: [14.2, 14.3, 14.4, 14.5, 14.5, 14.6, 14.7, 14.7, 14.8, 14.82]),
    ForexPair(pair: 'DOT',
        flag: '⚫🔵',
        price: 7.24,
        change: -0.18,
        changePct: -2.43,
        isUp: false,
        category: 'Crypto',
        spark: [7.5, 7.48, 7.45, 7.43, 7.40, 7.38, 7.35, 7.32, 7.28, 7.24]),
    // COMMODITIES
    ForexPair(pair: 'XAU/USD',
        flag: '🥇✨',
        price: 2347.0,
        change: 12.80,
        changePct: 0.55,
        isUp: true,
        category: 'Commodities',
        spark: [2330, 2335, 2338, 2336, 2340, 2339, 2343, 2342, 2346, 2347]),
    ForexPair(pair: 'XAG/USD',
        flag: '🥈✨',
        price: 29.84,
        change: 0.42,
        changePct: 1.43,
        isUp: true,
        category: 'Commodities',
        spark: [29.2, 29.4, 29.3, 29.5, 29.6, 29.6, 29.7, 29.7, 29.8, 29.84]),
    ForexPair(pair: 'WTI OIL',
        flag: '🛢️🔴',
        price: 78.43,
        change: -0.24,
        changePct: -0.31,
        isUp: false,
        category: 'Commodities',
        spark: [79.2, 79.0, 78.8, 78.9, 78.7, 78.8, 78.6, 78.7, 78.5, 78.43]),
    ForexPair(pair: 'BRENT',
        flag: '🛢️🔵',
        price: 82.17,
        change: -0.31,
        changePct: -0.38,
        isUp: false,
        category: 'Commodities',
        spark: [82.8, 82.6, 82.5, 82.4, 82.4, 82.3, 82.3, 82.2, 82.2, 82.17]),
    ForexPair(pair: 'NAT GAS',
        flag: '🔥⚡',
        price: 2.847,
        change: 0.043,
        changePct: 1.53,
        isUp: true,
        category: 'Commodities',
        spark: [2.78, 2.79, 2.80, 2.80, 2.81, 2.82, 2.83, 2.83, 2.84, 2.847]),
    ForexPair(pair: 'COPPER',
        flag: '🔶⚙️',
        price: 4.524,
        change: 0.082,
        changePct: 1.85,
        isUp: true,
        category: 'Commodities',
        spark: [4.42, 4.44, 4.46, 4.47, 4.48, 4.49, 4.50, 4.51, 4.52, 4.524]),
    ForexPair(pair: 'PLATINUM',
        flag: '⬜✨',
        price: 982.40,
        change: 8.60,
        changePct: 0.88,
        isUp: true,
        category: 'Commodities',
        spark: [970, 972, 974, 976, 977, 978, 979, 980, 981, 982.40]),
    ForexPair(pair: 'WHEAT',
        flag: '🌾🟡',
        price: 612.50,
        change: -8.40,
        changePct: -1.35,
        isUp: false,
        category: 'Commodities',
        spark: [624, 622, 620, 618, 617, 616, 615, 614, 613, 612.50]),
    ForexPair(pair: 'CORN',
        flag: '🌽🟡',
        price: 448.75,
        change: 4.25,
        changePct: 0.96,
        isUp: true,
        category: 'Commodities',
        spark: [442, 443, 444, 445, 446, 447, 447, 448, 448, 448.75]),
    ForexPair(pair: 'COTTON',
        flag: '☁️⚪',
        price: 82.34,
        change: -0.84,
        changePct: -1.01,
        isUp: false,
        category: 'Commodities',
        spark: [83.5, 83.3, 83.1, 82.9, 82.8, 82.7, 82.6, 82.5, 82.4, 82.34]),
    // FUTURES
    ForexPair(pair: 'ES1! SPX',
        flag: '📊🔮',
        price: 5482.50,
        change: 18.25,
        changePct: 0.33,
        isUp: true,
        category: 'Futures',
        spark: [5460, 5462, 5464, 5466, 5468, 5470, 5474, 5477, 5480, 5482.50]),
    ForexPair(pair: 'NQ1! NAS',
        flag: '💻🔮',
        price: 19842.0,
        change: -52.0,
        changePct: -0.26,
        isUp: false,
        category: 'Futures',
        spark: [
          19950,
          19930,
          19910,
          19890,
          19880,
          19870,
          19860,
          19855,
          19848,
          19842
        ]),
    ForexPair(pair: 'GC1! GOLD',
        flag: '🥇🔮',
        price: 2352.30,
        change: 14.60,
        changePct: 0.62,
        isUp: true,
        category: 'Futures',
        spark: [2334, 2336, 2338, 2340, 2342, 2344, 2346, 2348, 2350, 2352.30]),
    ForexPair(pair: 'CL1! OIL',
        flag: '🛢️🔮',
        price: 77.84,
        change: -0.58,
        changePct: -0.74,
        isUp: false,
        category: 'Futures',
        spark: [78.6, 78.4, 78.3, 78.2, 78.1, 78.1, 78.0, 77.9, 77.9, 77.84]),
    ForexPair(pair: 'ZB1! BOND',
        flag: '📜🔮',
        price: 118.42,
        change: 0.34,
        changePct: 0.29,
        isUp: true,
        category: 'Futures',
        spark: [
          118.0,
          118.05,
          118.1,
          118.15,
          118.2,
          118.25,
          118.3,
          118.35,
          118.4,
          118.42
        ]),
    ForexPair(pair: 'SI1! SILV',
        flag: '🥈🔮',
        price: 29.92,
        change: 0.48,
        changePct: 1.63,
        isUp: true,
        category: 'Futures',
        spark: [
          29.3,
          29.4,
          29.5,
          29.6,
          29.65,
          29.7,
          29.75,
          29.8,
          29.86,
          29.92
        ]),
    ForexPair(pair: 'HG1! COP',
        flag: '🔶🔮',
        price: 4.512,
        change: 0.074,
        changePct: 1.67,
        isUp: true,
        category: 'Futures',
        spark: [4.42, 4.44, 4.46, 4.47, 4.48, 4.49, 4.50, 4.50, 4.51, 4.512]),
    ForexPair(pair: 'YM1! DOW',
        flag: '🏦🔮',
        price: 39180.0,
        change: 98.0,
        changePct: 0.25,
        isUp: true,
        category: 'Futures',
        spark: [
          39060,
          39080,
          39095,
          39110,
          39120,
          39135,
          39150,
          39160,
          39170,
          39180
        ]),
  ];

  // ── NEWS ──
  static List<NewsItem> news = [
    // Forex
    NewsItem(source: 'REUTERS',
        timeAgo: '1h ago',
        sentiment: 'bearish',
        category: 'Forex',
        pairs: ['USD/JPY', 'EUR/USD'],
        url: 'https://reuters.com',
        title: 'Fed signals no rate cut until September as inflation remains sticky above 2.5% target'),
    NewsItem(source: 'BLOOMBERG',
        timeAgo: '2h ago',
        sentiment: 'bullish',
        category: 'Forex',
        pairs: ['EUR/USD', 'EUR/GBP'],
        url: 'https://bloomberg.com',
        title: 'ECB officials debate pace of easing as Eurozone growth surprises to the upside in Q2'),
    NewsItem(source: 'FOREXLIVE',
        timeAgo: '3h ago',
        sentiment: 'bullish',
        category: 'Forex',
        pairs: ['USD/JPY', 'GBP/JPY'],
        url: 'https://forexlive.com',
        title: 'BOJ meeting minutes suggest policy normalization on track, yen strengthens broadly'),
    NewsItem(source: 'FXSTREET',
        timeAgo: '4h ago',
        sentiment: 'bullish',
        category: 'Forex',
        pairs: ['GBP/USD'],
        url: 'https://fxstreet.com',
        title: 'UK GDP beats expectations at 0.4% — GBP gains across the board on positive data'),
    NewsItem(source: 'MARKETWATCH',
        timeAgo: '5h ago',
        sentiment: 'neutral',
        category: 'Forex',
        pairs: ['USD/CHF', 'EUR/CHF'],
        url: 'https://marketwatch.com',
        title: 'Swiss franc strengthens on geopolitical safe-haven flows as risk appetite dips globally'),
    // Indices
    NewsItem(source: 'CNBC',
        timeAgo: '1h ago',
        sentiment: 'bullish',
        category: 'Indices',
        pairs: ['S&P 500', 'NASDAQ'],
        url: 'https://cnbc.com',
        title: 'S&P 500 hits new all-time high as tech stocks rally on strong earnings season results'),
    NewsItem(source: 'BLOOMBERG',
        timeAgo: '2h ago',
        sentiment: 'bearish',
        category: 'Indices',
        pairs: ['NIKKEI', 'DAX 40'],
        url: 'https://bloomberg.com',
        title: 'Asian markets fall amid recession fears; Nikkei drops 0.54% on weak export data'),
    NewsItem(source: 'MARKETWATCH',
        timeAgo: '3h ago',
        sentiment: 'neutral',
        category: 'Indices',
        pairs: ['VIX', 'S&P 500'],
        url: 'https://marketwatch.com',
        title: 'VIX fear gauge drops to 13.4 as investor confidence grows despite rate uncertainty'),
    NewsItem(source: 'REUTERS',
        timeAgo: '5h ago',
        sentiment: 'bullish',
        category: 'Indices',
        pairs: ['FTSE 100'],
        url: 'https://reuters.com',
        title: 'FTSE 100 steady as UK services sector expands; bank stocks lead gains in London'),
    NewsItem(source: 'INVESTING',
        timeAgo: '6h ago',
        sentiment: 'bullish',
        category: 'Indices',
        pairs: ['DAX 40', 'CAC 40'],
        url: 'https://investing.com',
        title: 'European indices rise as PMI data beats expectations; DAX leads with 0.42% gain'),
    // Stocks
    NewsItem(source: 'CNBC',
        timeAgo: '30m ago',
        sentiment: 'bullish',
        category: 'Stocks',
        pairs: ['NVDA', 'AAPL'],
        url: 'https://cnbc.com',
        title: 'NVIDIA surges 3% after beating Q2 earnings — AI chip demand remains insatiable globally'),
    NewsItem(source: 'BLOOMBERG',
        timeAgo: '1h ago',
        sentiment: 'bearish',
        category: 'Stocks',
        pairs: ['TSLA'],
        url: 'https://bloomberg.com',
        title: 'Tesla shares slide 2.5% amid delivery miss concerns and growing EV market competition'),
    NewsItem(source: 'MARKETWATCH',
        timeAgo: '2h ago',
        sentiment: 'bullish',
        category: 'Stocks',
        pairs: ['AMZN', 'META'],
        url: 'https://marketwatch.com',
        title: 'Amazon and Meta lead tech rally as cloud and ad revenue beat analyst expectations'),
    NewsItem(source: 'INVESTING',
        timeAgo: '4h ago',
        sentiment: 'neutral',
        category: 'Stocks',
        pairs: ['MSFT', 'GOOGL'],
        url: 'https://investing.com',
        title: 'Microsoft and Alphabet report mixed results; AI investments weigh on short-term margins'),
    NewsItem(source: 'REUTERS',
        timeAgo: '5h ago',
        sentiment: 'bearish',
        category: 'Stocks',
        pairs: ['JPM', 'BABA'],
        url: 'https://reuters.com',
        title: 'Banking stocks under pressure as yield curve concerns persist; JPMorgan slides 0.9%'),
    // Crypto
    NewsItem(source: 'COINDESK',
        timeAgo: '45m ago',
        sentiment: 'bullish',
        category: 'Crypto',
        pairs: ['BTC/USD'],
        url: 'https://coindesk.com',
        title: 'Bitcoin surges past 68K as institutional inflows accelerate ahead of ETF expansion'),
    NewsItem(source: 'COINTELEGRAPH',
        timeAgo: '1h ago',
        sentiment: 'bearish',
        category: 'Crypto',
        pairs: ['ETH/USD'],
        url: 'https://cointelegraph.com',
        title: 'Ethereum drops 2.2% amid profit-taking; whale wallets show heavy selling pressure'),
    NewsItem(source: 'DECRYPT',
        timeAgo: '2h ago',
        sentiment: 'bullish',
        category: 'Crypto',
        pairs: ['SOL/USD', 'BNB/USD'],
        url: 'https://decrypt.co',
        title: 'Solana hits 3-month high on DeFi surge; total value locked exceeds 4.8 billion USD'),
    NewsItem(source: 'BLOOMBERG',
        timeAgo: '3h ago',
        sentiment: 'neutral',
        category: 'Crypto',
        pairs: ['XRP/USD'],
        url: 'https://bloomberg.com',
        title: 'XRP faces resistance at 0.60 as Ripple SEC case developments remain inconclusive'),
    NewsItem(source: 'COINDESK',
        timeAgo: '4h ago',
        sentiment: 'bullish',
        category: 'Crypto',
        pairs: ['DOGE', 'ADA/USD'],
        url: 'https://coindesk.com',
        title: 'Altcoins rally broadly as risk appetite returns; DOGE up 2.8% on social media buzz'),
    // Commodities
    NewsItem(source: 'REUTERS',
        timeAgo: '1h ago',
        sentiment: 'bullish',
        category: 'Commodities',
        pairs: ['XAU/USD'],
        url: 'https://reuters.com',
        title: 'Gold climbs to 2347 as safe-haven demand rises on Middle East geopolitical tensions'),
    NewsItem(source: 'OILPRICE',
        timeAgo: '2h ago',
        sentiment: 'bearish',
        category: 'Commodities',
        pairs: ['WTI OIL', 'BRENT'],
        url: 'https://oilprice.com',
        title: 'Oil prices fall 0.3% as US crude inventory build raises demand concern ahead of OPEC+'),
    NewsItem(source: 'KITCO',
        timeAgo: '3h ago',
        sentiment: 'bullish',
        category: 'Commodities',
        pairs: ['XAG/USD', 'PLATINUM'],
        url: 'https://kitco.com',
        title: 'Silver and platinum rally on green energy demand surge; industrial metals outperform'),
    NewsItem(source: 'AGRIMONEY',
        timeAgo: '5h ago',
        sentiment: 'bearish',
        category: 'Commodities',
        pairs: ['WHEAT', 'CORN'],
        url: 'https://agrimoney.com',
        title: 'Wheat futures tumble on bumper harvest forecasts from Ukraine and Russia supply zones'),
    NewsItem(source: 'REUTERS',
        timeAgo: '6h ago',
        sentiment: 'bullish',
        category: 'Commodities',
        pairs: ['COPPER', 'NAT GAS'],
        url: 'https://reuters.com',
        title: 'Copper hits 2-month high on China manufacturing recovery; natural gas up on hot weather'),
    // Futures
    NewsItem(source: 'CME GROUP',
        timeAgo: '1h ago',
        sentiment: 'bullish',
        category: 'Futures',
        pairs: ['ES1! SPX', 'YM1! DOW'],
        url: 'https://cmegroup.com',
        title: 'S&P futures climb ahead of key PCE inflation data; bulls target 5500 level this week'),
    NewsItem(source: 'BLOOMBERG',
        timeAgo: '2h ago',
        sentiment: 'bearish',
        category: 'Futures',
        pairs: ['NQ1! NAS'],
        url: 'https://bloomberg.com',
        title: 'Nasdaq futures slip as rate-sensitive tech names retreat on hawkish Fed commentary'),
    NewsItem(source: 'REUTERS',
        timeAgo: '3h ago',
        sentiment: 'bullish',
        category: 'Futures',
        pairs: ['GC1! GOLD', 'SI1! SILV'],
        url: 'https://reuters.com',
        title: 'Gold and silver futures surge as dollar weakens; precious metals break key resistance'),
    NewsItem(source: 'OILPRICE',
        timeAgo: '4h ago',
        sentiment: 'bearish',
        category: 'Futures',
        pairs: ['CL1! OIL'],
        url: 'https://oilprice.com',
        title: 'Crude oil futures decline on rising inventory data; traders await OPEC+ production call'),
  ];
  // ── CALENDAR ──
  static List<CalendarEvent> calendar = [
    // Forex
    CalendarEvent(time: '08:30', currency: 'USD', event: 'Core PCE Price Index m/m',  impact: 'HIGH', actual: '0.3%',   forecast: '0.2%',  previous: '0.1%',  isBetter: true,  category: 'Forex'),
    CalendarEvent(time: '09:00', currency: 'EUR', event: 'CPI Flash Estimate y/y',    impact: 'HIGH', actual: '—',      forecast: '2.5%',  previous: '2.6%',  isBetter: null,  category: 'Forex'),
    CalendarEvent(time: '10:30', currency: 'GBP', event: 'GDP m/m',                   impact: 'MED',  actual: '0.1%',   forecast: '0.2%',  previous: '0.3%',  isBetter: false, category: 'Forex'),
    CalendarEvent(time: '12:30', currency: 'USD', event: 'Non-Farm Payrolls',          impact: 'HIGH', actual: '—',      forecast: '190K',  previous: '175K',  isBetter: null,  category: 'Forex'),
    CalendarEvent(time: '14:00', currency: 'CAD', event: 'Ivey PMI',                   impact: 'MED',  actual: '—',      forecast: '55.1',  previous: '54.8',  isBetter: null,  category: 'Forex'),
    CalendarEvent(time: '15:30', currency: 'AUD', event: 'RBA Meeting Minutes',        impact: 'MED',  actual: '—',      forecast: '—',     previous: '—',     isBetter: null,  category: 'Forex'),
    CalendarEvent(time: '18:00', currency: 'JPY', event: 'BOJ Policy Rate Decision',   impact: 'HIGH', actual: '—',      forecast: '0.1%',  previous: '0.1%',  isBetter: null,  category: 'Forex'),
    CalendarEvent(time: '20:00', currency: 'NZD', event: 'Trade Balance',              impact: 'LOW',  actual: '—',      forecast: '-500M', previous: '-480M', isBetter: null,  category: 'Forex'),
    // Indices
    CalendarEvent(time: '09:30', currency: 'US',  event: 'S&P 500 Futures Open',       impact: 'HIGH', actual: '5482',   forecast: '5460',  previous: '5464',  isBetter: true,  category: 'Indices'),
    CalendarEvent(time: '14:30', currency: 'US',  event: 'ISM Manufacturing PMI',       impact: 'HIGH', actual: '—',      forecast: '49.8',  previous: '48.7',  isBetter: null,  category: 'Indices'),
    CalendarEvent(time: '15:00', currency: 'US',  event: 'Consumer Confidence Index',   impact: 'MED',  actual: '—',      forecast: '102.5', previous: '100.3', isBetter: null,  category: 'Indices'),
    CalendarEvent(time: '16:00', currency: 'EU',  event: 'Eurozone Composite PMI',      impact: 'MED',  actual: '51.3',   forecast: '50.8',  previous: '50.2',  isBetter: true,  category: 'Indices'),
    CalendarEvent(time: '07:00', currency: 'UK',  event: 'FTSE 100 Open',               impact: 'LOW',  actual: '8245',   forecast: '8260',  previous: '8264',  isBetter: false, category: 'Indices'),
    CalendarEvent(time: '08:00', currency: 'JP',  event: 'Nikkei 225 Open',             impact: 'LOW',  actual: '38920',  forecast: '39100', previous: '39130', isBetter: false, category: 'Indices'),
    // Stocks
    CalendarEvent(time: '07:30', currency: 'AAPL', event: 'Apple Q2 Earnings Report',   impact: 'HIGH', actual: '1.53',   forecast: '1.48',  previous: '1.40',  isBetter: true,  category: 'Stocks'),
    CalendarEvent(time: '08:00', currency: 'NVDA', event: 'NVIDIA Revenue Report',       impact: 'HIGH', actual: '—',      forecast: '28.6B', previous: '26B',   isBetter: null,  category: 'Stocks'),
    CalendarEvent(time: '09:00', currency: 'TSLA', event: 'Tesla Delivery Numbers',      impact: 'HIGH', actual: '443K',   forecast: '460K',  previous: '422K',  isBetter: false, category: 'Stocks'),
    CalendarEvent(time: '10:00', currency: 'MSFT', event: 'Microsoft Azure Growth',      impact: 'MED',  actual: '—',      forecast: '+29%',  previous: '+27%',  isBetter: null,  category: 'Stocks'),
    CalendarEvent(time: '13:00', currency: 'META', event: 'Meta Ad Revenue Report',      impact: 'MED',  actual: '39.1B',  forecast: '38.3B', previous: '36.5B', isBetter: true,  category: 'Stocks'),
    CalendarEvent(time: '15:00', currency: 'AMZN', event: 'Amazon AWS Revenue',          impact: 'HIGH', actual: '—',      forecast: '25.0B', previous: '23.2B', isBetter: null,  category: 'Stocks'),
    // Crypto
    CalendarEvent(time: '00:00', currency: 'BTC',  event: 'Bitcoin Halving Countdown',   impact: 'HIGH', actual: 'Done',   forecast: '—',     previous: 'Apr 24',isBetter: null,  category: 'Crypto'),
    CalendarEvent(time: '08:00', currency: 'ETH',  event: 'Ethereum Dencun Upgrade',     impact: 'HIGH', actual: 'Live',   forecast: '—',     previous: '—',     isBetter: null,  category: 'Crypto'),
    CalendarEvent(time: '12:00', currency: 'CFTC', event: 'Crypto COT Positions Update', impact: 'MED',  actual: '—',      forecast: '—',     previous: '—',     isBetter: null,  category: 'Crypto'),
    CalendarEvent(time: '16:00', currency: 'SEC',  event: 'ETF Approval Decision',       impact: 'HIGH', actual: '—',      forecast: 'YES',   previous: 'Pend',  isBetter: null,  category: 'Crypto'),
    CalendarEvent(time: '18:00', currency: 'FED',  event: 'Crypto Regulation Statement', impact: 'MED',  actual: '—',      forecast: '—',     previous: '—',     isBetter: null,  category: 'Crypto'),
    // Commodities
    CalendarEvent(time: '10:30', currency: 'EIA',  event: 'Crude Oil Inventories',       impact: 'HIGH', actual: '+2.4M',  forecast: '-0.8M', previous: '-3.2M', isBetter: false, category: 'Commodities'),
    CalendarEvent(time: '14:00', currency: 'OPEC', event: 'OPEC+ Production Decision',   impact: 'HIGH', actual: '—',      forecast: 'Hold',  previous: 'Cut',   isBetter: null,  category: 'Commodities'),
    CalendarEvent(time: '07:30', currency: 'GOLD', event: 'Gold Import Data India',       impact: 'MED',  actual: '52T',    forecast: '48T',   previous: '45T',   isBetter: true,  category: 'Commodities'),
    CalendarEvent(time: '11:00', currency: 'USDA', event: 'WASDE Crop Supply Report',    impact: 'HIGH', actual: '—',      forecast: '—',     previous: '—',     isBetter: null,  category: 'Commodities'),
    CalendarEvent(time: '15:00', currency: 'NGAS', event: 'Natural Gas Storage Change',  impact: 'MED',  actual: '+42B',   forecast: '+38B',  previous: '+29B',  isBetter: false, category: 'Commodities'),
    // Futures
    CalendarEvent(time: '09:30', currency: 'CME',  event: 'ES Futures Roll Date',        impact: 'MED',  actual: 'Q3',     forecast: '—',     previous: 'Q2',    isBetter: null,  category: 'Futures'),
    CalendarEvent(time: '13:30', currency: 'CBOT', event: 'Treasury Bond Auction',       impact: 'HIGH', actual: '—',      forecast: '4.28%', previous: '4.31%', isBetter: null,  category: 'Futures'),
    CalendarEvent(time: '14:00', currency: 'NYMX', event: 'Crude Futures Expiry',        impact: 'HIGH', actual: '—',      forecast: 'Jul',   previous: 'Jun',   isBetter: null,  category: 'Futures'),
    CalendarEvent(time: '15:30', currency: 'CME',  event: 'Gold Futures Open Interest',  impact: 'MED',  actual: '478K',   forecast: '470K',  previous: '465K',  isBetter: true,  category: 'Futures'),
    CalendarEvent(time: '16:00', currency: 'CME',  event: 'VIX Futures Settlement',      impact: 'MED',  actual: '—',      forecast: '13.8',  previous: '14.2',  isBetter: null,  category: 'Futures'),
  ];

  // ── COT DATA ──
  static List<CotData> cotData = [
    // Forex
    CotData(pair: 'EUR/USD', nonCommercialLong: 174820, nonCommercialShort: 112410, commercialLong: 98300,   commercialShort: 161500,  smallTraderLong: 42100,  smallTraderShort: 41310,  weekEnding: 'Jun 24, 2026', openInterest: 478000,  category: 'Forex'),
    CotData(pair: 'GBP/USD', nonCommercialLong: 62400,  nonCommercialShort: 48200,  commercialLong: 54100,   commercialShort: 69800,   smallTraderLong: 18200,  smallTraderShort: 16700,  weekEnding: 'Jun 24, 2026', openInterest: 253000,  category: 'Forex'),
    CotData(pair: 'USD/JPY', nonCommercialLong: 48900,  nonCommercialShort: 91200,  commercialLong: 82100,   commercialShort: 42300,   smallTraderLong: 21100,  smallTraderShort: 18600,  weekEnding: 'Jun 24, 2026', openInterest: 304000,  category: 'Forex'),
    CotData(pair: 'AUD/USD', nonCommercialLong: 38200,  nonCommercialShort: 52700,  commercialLong: 61400,   commercialShort: 49200,   smallTraderLong: 14300,  smallTraderShort: 12000,  weekEnding: 'Jun 24, 2026', openInterest: 228000,  category: 'Forex'),
    CotData(pair: 'USD/CAD', nonCommercialLong: 31500,  nonCommercialShort: 24800,  commercialLong: 38900,   commercialShort: 46300,   smallTraderLong: 11200,  smallTraderShort: 10300,  weekEnding: 'Jun 24, 2026', openInterest: 163000,  category: 'Forex'),
    // Indices
    CotData(pair: 'S&P 500', nonCommercialLong: 284200, nonCommercialShort: 142800, commercialLong: 168400,  commercialShort: 312000,  smallTraderLong: 84200,  smallTraderShort: 82000,  weekEnding: 'Jun 24, 2026', openInterest: 892000,  category: 'Indices'),
    CotData(pair: 'NASDAQ',  nonCommercialLong: 142600, nonCommercialShort: 98400,  commercialLong: 112000,  commercialShort: 158200,  smallTraderLong: 42800,  smallTraderShort: 40800,  weekEnding: 'Jun 24, 2026', openInterest: 548000,  category: 'Indices'),
    CotData(pair: 'DOW',     nonCommercialLong: 82400,  nonCommercialShort: 64200,  commercialLong: 74800,   commercialShort: 94600,   smallTraderLong: 28400,  smallTraderShort: 26800,  weekEnding: 'Jun 24, 2026', openInterest: 371000,  category: 'Indices'),
    CotData(pair: 'NIKKEI',  nonCommercialLong: 48200,  nonCommercialShort: 82400,  commercialLong: 74200,   commercialShort: 42800,   smallTraderLong: 18400,  smallTraderShort: 17600,  weekEnding: 'Jun 24, 2026', openInterest: 283000,  category: 'Indices'),
    // Stocks
    CotData(pair: 'SPY ETF', nonCommercialLong: 384200, nonCommercialShort: 182400, commercialLong: 224000,  commercialShort: 428000,  smallTraderLong: 124000, smallTraderShort: 122000, weekEnding: 'Jun 24, 2026', openInterest: 1464000, category: 'Stocks'),
    CotData(pair: 'QQQ ETF', nonCommercialLong: 214800, nonCommercialShort: 148200, commercialLong: 168400,  commercialShort: 236000,  smallTraderLong: 82400,  smallTraderShort: 80800,  weekEnding: 'Jun 24, 2026', openInterest: 930600,  category: 'Stocks'),
    CotData(pair: 'IWM ETF', nonCommercialLong: 84200,  nonCommercialShort: 112400, commercialLong: 98400,   commercialShort: 72800,   smallTraderLong: 32400,  smallTraderShort: 30200,  weekEnding: 'Jun 24, 2026', openInterest: 430400,  category: 'Stocks'),
    // Crypto
    CotData(pair: 'BTC/USD', nonCommercialLong: 28400,  nonCommercialShort: 14200,  commercialLong: 18400,   commercialShort: 32800,   smallTraderLong: 8400,   smallTraderShort: 8200,   weekEnding: 'Jun 24, 2026', openInterest: 110400,  category: 'Crypto'),
    CotData(pair: 'ETH/USD', nonCommercialLong: 14200,  nonCommercialShort: 18400,  commercialLong: 12400,   commercialShort: 9800,    smallTraderLong: 4200,   smallTraderShort: 4100,   weekEnding: 'Jun 24, 2026', openInterest: 63100,   category: 'Crypto'),
    // Commodities
    CotData(pair: 'XAU/USD', nonCommercialLong: 284200, nonCommercialShort: 98400,  commercialLong: 112400,  commercialShort: 298000,  smallTraderLong: 68400,  smallTraderShort: 68000,  weekEnding: 'Jun 24, 2026', openInterest: 930400,  category: 'Commodities'),
    CotData(pair: 'XAG/USD', nonCommercialLong: 84200,  nonCommercialShort: 42400,  commercialLong: 48400,   commercialShort: 90800,   smallTraderLong: 24400,  smallTraderShort: 23800,  weekEnding: 'Jun 24, 2026', openInterest: 314000,  category: 'Commodities'),
    CotData(pair: 'WTI OIL', nonCommercialLong: 384200, nonCommercialShort: 214800, commercialLong: 242400,  commercialShort: 412800,  smallTraderLong: 98400,  smallTraderShort: 97200,  weekEnding: 'Jun 24, 2026', openInterest: 1449800, category: 'Commodities'),
    CotData(pair: 'WHEAT',   nonCommercialLong: 42400,  nonCommercialShort: 84200,  commercialLong: 78400,   commercialShort: 38800,   smallTraderLong: 18400,  smallTraderShort: 17800,  weekEnding: 'Jun 24, 2026', openInterest: 280000,  category: 'Commodities'),
    CotData(pair: 'CORN',    nonCommercialLong: 84200,  nonCommercialShort: 142400, commercialLong: 138400,  commercialShort: 82800,   smallTraderLong: 38400,  smallTraderShort: 37800,  weekEnding: 'Jun 24, 2026', openInterest: 524000,  category: 'Commodities'),
    // Futures
    CotData(pair: 'ES1! SPX',nonCommercialLong: 184200, nonCommercialShort: 84200,  commercialLong: 98400,   commercialShort: 198800,  smallTraderLong: 54200,  smallTraderShort: 53800,  weekEnding: 'Jun 24, 2026', openInterest: 673600,  category: 'Futures'),
    CotData(pair: 'GC1! GLD',nonCommercialLong: 214200, nonCommercialShort: 84800,  commercialLong: 98400,   commercialShort: 228000,  smallTraderLong: 54800,  smallTraderShort: 54400,  weekEnding: 'Jun 24, 2026', openInterest: 734600,  category: 'Futures'),
    CotData(pair: 'CL1! OIL',nonCommercialLong: 284200, nonCommercialShort: 184200, commercialLong: 198400,  commercialShort: 298800,  smallTraderLong: 82400,  smallTraderShort: 82000,  weekEnding: 'Jun 24, 2026', openInterest: 1130000, category: 'Futures'),
    CotData(pair: 'NQ1! NAS',nonCommercialLong: 124200, nonCommercialShort: 84800,  commercialLong: 88400,   commercialShort: 128000,  smallTraderLong: 42400,  smallTraderShort: 42000,  weekEnding: 'Jun 24, 2026', openInterest: 510000,  category: 'Futures'),
  ];

  // ── SENTIMENT ──
  static List<SentimentData> sentiment = [
    // Forex
    SentimentData(pair: 'EUR/USD',   longPct: 58.4, shortPct: 41.6, source: 'Myfxbook',  category: 'Forex'),
    SentimentData(pair: 'GBP/USD',   longPct: 44.2, shortPct: 55.8, source: 'Myfxbook',  category: 'Forex'),
    SentimentData(pair: 'USD/JPY',   longPct: 62.7, shortPct: 37.3, source: 'Myfxbook',  category: 'Forex'),
    SentimentData(pair: 'AUD/USD',   longPct: 49.1, shortPct: 50.9, source: 'Myfxbook',  category: 'Forex'),
    SentimentData(pair: 'USD/CAD',   longPct: 38.6, shortPct: 61.4, source: 'Myfxbook',  category: 'Forex'),
    SentimentData(pair: 'NZD/USD',   longPct: 52.3, shortPct: 47.7, source: 'Myfxbook',  category: 'Forex'),
    // Indices
    SentimentData(pair: 'S&P 500',   longPct: 72.4, shortPct: 27.6, source: 'IG Group',  category: 'Indices'),
    SentimentData(pair: 'NASDAQ',    longPct: 68.2, shortPct: 31.8, source: 'IG Group',  category: 'Indices'),
    SentimentData(pair: 'DOW JONES', longPct: 65.8, shortPct: 34.2, source: 'IG Group',  category: 'Indices'),
    SentimentData(pair: 'NIKKEI',    longPct: 34.2, shortPct: 65.8, source: 'IG Group',  category: 'Indices'),
    SentimentData(pair: 'DAX 40',    longPct: 61.4, shortPct: 38.6, source: 'IG Group',  category: 'Indices'),
    SentimentData(pair: 'FTSE 100',  longPct: 55.8, shortPct: 44.2, source: 'IG Group',  category: 'Indices'),
    // Stocks
    SentimentData(pair: 'AAPL',      longPct: 78.4, shortPct: 21.6, source: 'Finviz',    category: 'Stocks'),
    SentimentData(pair: 'TSLA',      longPct: 42.8, shortPct: 57.2, source: 'Finviz',    category: 'Stocks'),
    SentimentData(pair: 'NVDA',      longPct: 82.4, shortPct: 17.6, source: 'Finviz',    category: 'Stocks'),
    SentimentData(pair: 'MSFT',      longPct: 74.2, shortPct: 25.8, source: 'Finviz',    category: 'Stocks'),
    SentimentData(pair: 'AMZN',      longPct: 76.8, shortPct: 23.2, source: 'Finviz',    category: 'Stocks'),
    SentimentData(pair: 'META',      longPct: 71.4, shortPct: 28.6, source: 'Finviz',    category: 'Stocks'),
    // Crypto
    SentimentData(pair: 'BTC/USD',   longPct: 71.2, shortPct: 28.8, source: 'Myfxbook',  category: 'Crypto'),
    SentimentData(pair: 'ETH/USD',   longPct: 54.8, shortPct: 45.2, source: 'Myfxbook',  category: 'Crypto'),
    SentimentData(pair: 'SOL/USD',   longPct: 68.4, shortPct: 31.6, source: 'Myfxbook',  category: 'Crypto'),
    SentimentData(pair: 'XRP/USD',   longPct: 42.4, shortPct: 57.6, source: 'Myfxbook',  category: 'Crypto'),
    SentimentData(pair: 'BNB/USD',   longPct: 58.2, shortPct: 41.8, source: 'Myfxbook',  category: 'Crypto'),
    SentimentData(pair: 'DOGE',      longPct: 76.4, shortPct: 23.6, source: 'Myfxbook',  category: 'Crypto'),
    // Commodities
    SentimentData(pair: 'XAU/USD',   longPct: 74.8, shortPct: 25.2, source: 'Myfxbook',  category: 'Commodities'),
    SentimentData(pair: 'XAG/USD',   longPct: 62.4, shortPct: 37.6, source: 'Myfxbook',  category: 'Commodities'),
    SentimentData(pair: 'WTI OIL',   longPct: 38.4, shortPct: 61.6, source: 'Myfxbook',  category: 'Commodities'),
    SentimentData(pair: 'NAT GAS',   longPct: 44.8, shortPct: 55.2, source: 'Myfxbook',  category: 'Commodities'),
    SentimentData(pair: 'COPPER',    longPct: 67.4, shortPct: 32.6, source: 'Myfxbook',  category: 'Commodities'),
    SentimentData(pair: 'WHEAT',     longPct: 32.4, shortPct: 67.6, source: 'Myfxbook',  category: 'Commodities'),
    // Futures
    SentimentData(pair: 'ES1! SPX',  longPct: 68.4, shortPct: 31.6, source: 'CME',       category: 'Futures'),
    SentimentData(pair: 'GC1! GOLD', longPct: 72.4, shortPct: 27.6, source: 'CME',       category: 'Futures'),
    SentimentData(pair: 'CL1! OIL',  longPct: 36.8, shortPct: 63.2, source: 'CME',       category: 'Futures'),
    SentimentData(pair: 'NQ1! NAS',  longPct: 64.2, shortPct: 35.8, source: 'CME',       category: 'Futures'),
    SentimentData(pair: 'ZB1! BOND', longPct: 42.8, shortPct: 57.2, source: 'CME',       category: 'Futures'),
  ];

  // ── DATA SOURCES ──
  static List<DataSource> sources = [
    DataSource(icon: '🏛️', name: 'CFTC.GOV',      description: 'Official US government source for weekly COT reports. 100% free, no key required.',             tag: 'FREE · OFFICIAL', url: 'https://publicreporting.cftc.gov',       category: 'COT Data'),
    DataSource(icon: '📡', name: 'FINNHUB',        description: 'Real-time forex, stocks, crypto quotes, news sentiment and technical indicators.',               tag: 'FREE API',        url: 'https://finnhub.io',                     category: 'Prices & News'),
    DataSource(icon: '📈', name: 'ALPHA VANTAGE',  description: 'Historical OHLCV data for forex, stocks, crypto and economic indicators. 25 per day free.',     tag: 'FREE API',        url: 'https://alphavantage.co',                category: 'Historical Data'),
    DataSource(icon: '⚡', name: 'TWELVE DATA',    description: 'Ultra-low latency streaming for forex, stocks, indices and crypto. 800 credits per day free.',   tag: 'FREE TIER',       url: 'https://twelvedata.com',                 category: 'Streaming'),
    DataSource(icon: '📰', name: 'FOREXNEWSAPI',   description: 'Curated market news with AI sentiment for forex, stocks, crypto and commodities.',              tag: 'FREE TIER',       url: 'https://forexnewsapi.com',               category: 'News & Sentiment'),
    DataSource(icon: '📅', name: 'ECON. CALENDAR', description: 'High-impact events: NFP, CPI, GDP, earnings, OPEC, crypto events. Updates every 5 minutes.',    tag: 'FREE API',        url: 'https://rapidapi.com',                   category: 'Calendar'),
    DataSource(icon: '🌐', name: 'MYFXBOOK',       description: 'Retail trader sentiment, COT data, forex and commodities correlation and market hours.',         tag: 'FREE API',        url: 'https://myfxbook.com',                   category: 'Sentiment'),
    DataSource(icon: '📊', name: 'BARCHART',       description: 'Free COT charts for forex, futures, commodities and indices. Updated every Friday.',             tag: 'FREE WEBSITE',    url: 'https://barchart.com/forex/cot-reports', category: 'COT Data'),
    DataSource(icon: '💹', name: 'YAHOO FINANCE',  description: 'Free stock, ETF, index, crypto and commodity data. Widely used for historical price downloads.',  tag: 'FREE',            url: 'https://finance.yahoo.com',              category: 'Stocks & Indices'),
    DataSource(icon: '₿',  name: 'COINDESK',       description: 'Real-time crypto news, prices, on-chain data and market analysis for all major coins.',          tag: 'FREE',            url: 'https://coindesk.com',                   category: 'Crypto News'),
    DataSource(icon: '🛢️', name: 'EIA.GOV',        description: 'Official US Energy Information Administration — crude oil, gas and energy inventory data.',      tag: 'FREE · OFFICIAL', url: 'https://eia.gov',                        category: 'Commodities'),
    DataSource(icon: '🤖', name: 'CLAUDE AI',       description: 'AI analyst by Anthropic — explains market moves, COT, earnings and news for all asset classes.',tag: 'AI POWERED',      url: 'https://anthropic.com',                  category: 'AI Analysis'),
  ];
}